"""The ADAPTER unit's registration manifest + the surface-based compatibility matcher (CR-17 pt 2, stage 4). Pass-2 Thread 3: registration/discovery = per-unit manifests generated in-env and found by `discover_manifests()`; compatibility is DERIVED, not declared — the capability records only its structural surface, the adapter declares its protocol (recorded here as member names + parameter lists), and the substrate matches manifest-vs-manifest. Works against UNLOADED capabilities with zero protocol imports host-side.

Docs: https://cj-mills.github.io/cjm-substratecore/adapter_manifest.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/core/adapter_manifest.ipynb.

# %% auto #0
__all__ = ['AdapterManifest', 'adapter_manifest_from_dict', 'is_adapter_manifest', 'match_protocol_against_surface']

# %% ../../nbs/core/adapter_manifest.ipynb #9ae1b67e
import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional

# %% ../../nbs/core/adapter_manifest.ipynb #2b540d59
@dataclass
class AdapterManifest:
    """A discovered ADAPTER unit (CR-17 pt 2) — the registration record for one
    task-adapter implementation installed in some tool's worker env.

    Generated in-env by `cjm-ctl generate-adapter-manifest` (the protocol
    members are introspected where the protocol is importable); discovered
    host-side beside capability manifests via the `unit` discriminator.
    """
    name: str  # Unique unit name ("module.ClassName")
    version: str  # Interface-lib version at generation
    task_name: str  # The task this adapter serves (e.g. "graph-storage")
    module: str  # Impl module (importable in the tool's worker env)
    class_name: str  # Impl class name
    required_tool_protocol: str  # Protocol FQN (semantic contract; host never imports it)
    protocol_members: Dict[str, Any] = field(default_factory=dict)  # {"methods": [{"name","signature","params"}], "properties": [...]}
    conda_env: str = ""  # Env the manifest was generated from
    generated_at: str = ""  # ISO timestamp
    unit: str = "adapter"  # Manifest-kind discriminator

    def to_dict(self) -> Dict[str, Any]:  # JSON-ready dict ("class" key on disk)
        """Serialize to the on-disk JSON shape."""
        return {
            "unit": self.unit,
            "name": self.name,
            "version": self.version,
            "task_name": self.task_name,
            "module": self.module,
            "class": self.class_name,
            "required_tool_protocol": self.required_tool_protocol,
            "protocol_members": self.protocol_members,
            "conda_env": self.conda_env,
            "generated_at": self.generated_at,
        }

# %% ../../nbs/core/adapter_manifest.ipynb #9b9c0db2
def adapter_manifest_from_dict(
    d: Dict[str, Any],  # On-disk JSON dict (the "class" key maps to class_name)
) -> AdapterManifest:  # Typed adapter manifest
    """Reconstruct an `AdapterManifest` from its on-disk JSON shape."""
    return AdapterManifest(
        name=d["name"],
        version=d.get("version", "0.0.0"),
        task_name=d["task_name"],
        module=d["module"],
        class_name=d["class"],
        required_tool_protocol=d.get("required_tool_protocol", ""),
        protocol_members=d.get("protocol_members", {}),
        conda_env=d.get("conda_env", ""),
        generated_at=d.get("generated_at", ""),
    )

# %% ../../nbs/core/adapter_manifest.ipynb #60381422
def is_adapter_manifest(
    data: Any,  # Raw JSON-decoded manifest content
) -> bool:  # True when the payload declares the adapter unit kind
    """Route a manifest file by the `unit` discriminator (capability manifests
    carry no `unit` key; checked BEFORE `load_manifest` parsing)."""
    return isinstance(data, dict) and data.get("unit") == "adapter"

# %% ../../nbs/core/adapter_manifest.ipynb #3d4ab804
def match_protocol_against_surface(
    protocol_members: Dict[str, Any],  # {"methods": [...], "properties": [...]} from the adapter manifest
    structural_surface: Optional[Dict[str, Any]],  # Capability manifest code.structural_surface (None = pre-fracture)
) -> Dict[str, Any]:  # {"compatible", "missing_methods", "missing_properties", "param_mismatches", "reason"}
    """Surface-based compatibility (pass-2 Thread 3) — host-side, manifest-vs-
    manifest, safe against UNLOADED capabilities.

    Method rule: same name present + (when both sides record params) the
    surface params must START WITH the protocol params (prefix rule).
    Property rule: name present in the surface's properties.
    No surface recorded -> NOT compatible, with the reason spelled out.
    """
    if not structural_surface:
        return {"compatible": False, "missing_methods": [], "missing_properties": [],
                "param_mismatches": [],
                "reason": "capability manifest has no structural_surface "
                          "(pre-fracture; regenerate the manifest)"}
    surface_methods = {m.get("name"): m for m in structural_surface.get("methods", [])}
    surface_props = set(structural_surface.get("properties", []))
    missing_methods: List[str] = []
    param_mismatches: List[Dict[str, Any]] = []
    for pm in protocol_members.get("methods", []):
        sm = surface_methods.get(pm.get("name"))
        if sm is None:
            missing_methods.append(pm.get("name"))
            continue
        p_params, s_params = pm.get("params"), sm.get("params")
        if p_params and s_params is not None:
            if list(s_params[:len(p_params)]) != list(p_params):
                param_mismatches.append({
                    "method": pm.get("name"),
                    "protocol_params": list(p_params),
                    "surface_params": list(s_params),
                })
    missing_properties = [p for p in protocol_members.get("properties", [])
                          if p not in surface_props]
    compatible = not (missing_methods or missing_properties or param_mismatches)
    return {"compatible": compatible, "missing_methods": missing_methods,
            "missing_properties": missing_properties,
            "param_mismatches": param_mismatches, "reason": None}
