"""Typed data transfer at the worker boundary — the zero-copy `FileBackedDTO`
protocol and (stage 2 of the post-pass-2 execution sequence) the typed
result envelope that carries task results across the worker HTTP/JSON
boundary, retiring the per-consumer `field_of` dict-or-object tolerance
helpers (pass-2 Thread 3; evidence E5/D10/C7).

Docs: https://cj-mills.github.io/cjm-substratecore/wire.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/core/wire.ipynb.

# %% auto #0
__all__ = ['WIRE_KIND_KEY', 'WIRE_DATA_KEY', 'ENVELOPE_BODY_KEY', 'ACCOUNTS_HEADER', 'FileBackedDTO', 'flat_from_dict',
           'wire_type', 'wire_encode', 'wire_decode', 'CallEnvelope', 'set_call_envelope', 'reset_call_envelope',
           'get_call_envelope', 'begin_account_capture', 'record_account', 'drain_accounts']

# %% ../../nbs/core/wire.ipynb #6c220466
import dataclasses
import logging
from typing import Any, Callable, Dict, Protocol, runtime_checkable

_logger = logging.getLogger(__name__)

# %% ../../nbs/core/wire.ipynb #so9ttuo6zo
@runtime_checkable
class FileBackedDTO(Protocol):
    """Protocol for Data Transfer Objects that serialize to disk for zero-copy transfer."""
    
    def to_temp_file(self) -> str: # Absolute path to the temporary file
        """Save the data to a temporary file and return the absolute path."""
        ...

# %% ../../nbs/core/wire.ipynb #778f55f5
# Wire format constants + registries. kind -> class for decode;
# class -> kind (exact type) for encode.
WIRE_KIND_KEY = "__wire__"
WIRE_DATA_KEY = "data"

_WIRE_TYPES: Dict[str, type] = {}
_WIRE_KINDS: Dict[type, str] = {}

# %% ../../nbs/core/wire.ipynb #0ed275c5
def flat_from_dict(
    cls,      # The wire DTO dataclass being reconstructed
    d: dict,  # The envelope's "data" payload
):            # An instance of `cls`
    """Default reconstruction for FLAT wire DTOs (no nested-DTO fields).

    Filters the payload to the dataclass's declared fields (unknown extras
    are dropped with a debug log — transport-terminus tolerance, see the
    envelope design note) and lets the constructor enforce required fields
    (a missing required field raises TypeError loudly). DTOs with nested
    DTO fields (e.g. a result carrying a list of typed items) must define
    their own `from_dict` classmethod; `@wire_type` only attaches this
    default when the class has none.
    """
    names = {f.name for f in dataclasses.fields(cls)}
    extras = set(d) - names
    if extras:
        _logger.debug("wire: dropping unknown keys %s for %s",
                      sorted(extras), cls.__name__)
    return cls(**{k: v for k, v in d.items() if k in names})

# %% ../../nbs/core/wire.ipynb #fb9c37ec
def wire_type(
    kind: str  # Stable wire discriminator, e.g. "transcription.result"
) -> Callable[[type], type]:  # Class decorator
    """Register a dataclass as a typed wire DTO under `kind`.

    - The class must be a dataclass (encode falls back to
      `dataclasses.asdict` when it defines no `to_dict`).
    - If the class defines no `from_dict`, the flat default
      (`flat_from_dict`) is attached; nested DTOs define their own.
    - Re-registering the same LOGICAL class (qualname match; the module is
      ignored because nbdev's literate workflow defines each class twice —
      in-notebook `__main__` + the exported module) replaces the decode
      entry; a DIFFERENT class claiming an already-registered kind raises
      ValueError.
    """
    def decorator(cls: type) -> type:
        if not dataclasses.is_dataclass(cls):
            raise TypeError(f"@wire_type({kind!r}) requires a dataclass, got {cls!r}")
        existing = _WIRE_TYPES.get(kind)
        if existing is not None and existing.__qualname__ != cls.__qualname__:
            raise ValueError(
                f"wire kind {kind!r} already registered to "
                f"{existing.__module__}.{existing.__qualname__}")
        # The MODULE is deliberately NOT compared: nbdev's literate workflow
        # defines the same logical class twice (in-notebook `__main__` + the
        # exported module import), and both can coexist in one process (e.g.
        # nbdev-test --n_workers 1 runs sibling notebooks in one worker). Both
        # registrations stay encodable (the prior class keeps its _WIRE_KINDS
        # entry); decode resolves to the most recently registered definition.
        if getattr(cls, "from_dict", None) is None:
            cls.from_dict = classmethod(flat_from_dict)
        _WIRE_TYPES[kind] = cls
        _WIRE_KINDS[cls] = kind
        return cls
    return decorator

# %% ../../nbs/core/wire.ipynb #4fdcbc79
def wire_encode(
    obj: Any  # A task result (any shape)
) -> Any:     # Tagged envelope dict for registered DTOs; `obj` unchanged otherwise
    """Wrap a registered wire DTO in its tagged envelope (worker side).

    Exact-type lookup: subclasses are NOT encoded under the parent's kind
    (they pass through unregistered, preserving today's behavior).
    Payload preference: the DTO's own `to_dict()` when defined, else
    `dataclasses.asdict` (recursive — nested dataclasses flatten).
    """
    kind = _WIRE_KINDS.get(type(obj))
    if kind is None:
        return obj
    to_dict = getattr(obj, "to_dict", None)
    data = to_dict() if callable(to_dict) else dataclasses.asdict(obj)
    return {WIRE_KIND_KEY: kind, WIRE_DATA_KEY: data}


# %% ../../nbs/core/wire.ipynb #2ea90df5
def wire_decode(
    obj: Any  # A JSON-decoded response body (any shape)
) -> Any:     # The typed DTO for known kinds; `obj` unchanged otherwise
    """Reconstruct a typed result from its tagged envelope (host side).

    Known kind -> the registered class's `from_dict` (strict: a missing
    required field raises). Unknown kind -> the dict passes through
    UNCHANGED with the envelope intact (tolerant degradation for hosts
    without the result's interface library). Untagged values pass through.
    """
    if not (isinstance(obj, dict) and WIRE_KIND_KEY in obj):
        return obj
    cls = _WIRE_TYPES.get(obj.get(WIRE_KIND_KEY))
    if cls is None:
        return obj
    return cls.from_dict(obj.get(WIRE_DATA_KEY) or {})

# %% ../../nbs/core/wire.ipynb #7201b488
import contextvars
from dataclasses import dataclass, field, fields as _dc_fields
from typing import Optional

ENVELOPE_BODY_KEY = "envelope"  # Top-level request-body key (never inside kwargs)


@dataclass
class CallEnvelope:
    """Substrate-owned per-call identity + control block (CR-14 / CR-15).

    Travels as a top-level `"envelope"` key on every proxy→worker call body.
    All fields optional — an envelope-less call (direct proxy use, old hosts)
    simply yields unattributed records, never a failure.
    """
    job_id: Optional[str] = None  # Queue job identity
    run_id: Optional[str] = None  # Host-tier run correlation (core run manifests)
    composition_id: Optional[str] = None  # Stage-3 composition correlation
    node_id: Optional[str] = None  # Composition node correlation
    actor: Optional[str] = None  # Who/what initiated (operator / agent / host id)
    control: dict = field(default_factory=dict)  # Per-call flags (force/cache-bypass — the 4th CR-15 category)

    def to_wire(self) -> dict:
        """Compact wire form: None fields dropped; empty control dropped."""
        out = {}
        for f in _dc_fields(self):
            v = getattr(self, f.name)
            if v is None or (f.name == "control" and not v):
                continue
            out[f.name] = v
        return out

    @classmethod
    def from_wire(cls, d: dict) -> "CallEnvelope":
        """Tolerant decode: unknown keys ignored (forward compat)."""
        names = {f.name for f in _dc_fields(cls)}
        return cls(**{k: v for k, v in (d or {}).items() if k in names})


# The call-identity contextvar. The HOST sets it around job execution (the
# whole queue→manager→proxy chain is one async task, so it propagates to the
# proxy's payload construction); the WORKER endpoint re-sets it from the
# decoded wire envelope so in-worker code (the diagnostics handler) sees the
# same identity. Default None = honestly unattributed.
_CALL_ENVELOPE: contextvars.ContextVar[Optional[CallEnvelope]] = contextvars.ContextVar(
    "cjm_call_envelope", default=None)


def set_call_envelope(env: Optional[CallEnvelope]) -> contextvars.Token:
    """Set the current call envelope; returns the token for `reset_call_envelope`."""
    return _CALL_ENVELOPE.set(env)


def reset_call_envelope(token: contextvars.Token) -> None:
    """Restore the prior envelope (always pair with `set_call_envelope` in finally)."""
    _CALL_ENVELOPE.reset(token)


def get_call_envelope() -> Optional[CallEnvelope]:
    """The current call envelope, or None outside any call span."""
    return _CALL_ENVELOPE.get()

# %% ../../nbs/core/wire.ipynb #b8096dfe
ACCOUNTS_HEADER = "X-CJM-Accounts"  # Response header carrying recorded accounts (ASCII JSON)

# The per-call account accumulator. The worker endpoint begins a fresh
# capture beside the envelope decode; the executor thread shares the SAME
# list object via copy_context, so appends from capability-thread code are
# visible to the request task that drains them. Default None = no capture
# span (record_account no-ops).
_CALL_ACCOUNTS: contextvars.ContextVar[Optional[list]] = contextvars.ContextVar(
    "cjm_call_accounts", default=None)


def begin_account_capture() -> None:
    """Start a fresh account list for the current call span (worker endpoint
    entry; same no-reset semantics as the envelope — the ASGI request task's
    context dies with the request)."""
    _CALL_ACCOUNTS.set([])


def record_account(
    event_type: str,  # SubstrateEventType value (task_account / result_saved / cache_hit / ...)
    payload: Optional[dict] = None,  # Structured detail (references + hashes, never content)
) -> None:
    """Record one substrate-family account for the current call span.

    Called by the worker itself and by interface-lib storage helpers.
    Silent no-op outside a capture span (standalone runs, host imports) —
    the envelope-less-call posture applied to accounts.
    """
    lst = _CALL_ACCOUNTS.get()
    if lst is None:
        return
    lst.append({"event_type": event_type, "payload": payload or {}})


def drain_accounts() -> list:
    """Return + clear the current span's recorded accounts ([] outside a span
    or when nothing was recorded). The worker response path calls this once
    when building the response headers."""
    lst = _CALL_ACCOUNTS.get()
    if not lst:
        return []
    _CALL_ACCOUNTS.set([])
    return lst
