"""Shared GPU/CPU attribution helpers used by both `JobQueue._sample_resource_snapshot` (CR-6 Stage 3) and `CapabilityManager._record_sample_safe` (CR-7).

Docs: https://cj-mills.github.io/cjm-plugin-systemcore/telemetry.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/core/telemetry.ipynb.

# %% auto #0
__all__ = ['attribute_gpu_to_worker_subtree']

# %% ../../nbs/core/telemetry.ipynb #exports
from typing import Any, Dict, Iterable, Optional

# %% ../../nbs/core/telemetry.ipynb #attr-fn
def _proc_field(proc: Any, key: str, default: Any = None) -> Any:
    """Read a field from a sysmon process record, accepting dict or dataclass.

    `MonitorToolProtocol.list_processes()` returns `ProcessStats` dataclasses (CR-3),
    but proxy round-trips frequently coerce to dicts. Accept both so the
    helper works against either form without the caller pre-normalizing.
    """
    if isinstance(proc, dict):
        return proc.get(key, default)
    return getattr(proc, key, default)


def _worker_subtree_pids(stats: Dict[str, Any]) -> set:
    """Build the worker subtree PID set from a `/stats` dict.

    Falls back to a single-pid set when `subtree_pids` is absent (pre-fix
    workers, mock test fixtures). The worker pid itself is always included.
    """
    tree: set = set()
    worker_pid = stats.get('pid')
    if worker_pid is not None:
        tree.add(worker_pid)
    for sub_pid in (stats.get('subtree_pids') or ()):
        if sub_pid is not None:
            tree.add(sub_pid)
    return tree


def attribute_gpu_to_worker_subtree(
    stats: Dict[str, Any],  # Worker `/stats` payload (must include 'pid'; uses 'subtree_pids' if present)
    sysmon: Any,            # The configured monitor capability (or None)
) -> Optional[Dict[str, Any]]:
    """Attribute GPU memory across the worker's process subtree.

    Returns `{'gpu_memory_mb': float, 'gpu_index': Optional[int]}` when sysmon
    is reachable, or `None` when sysmon isn't configured / doesn't expose
    `list_processes()` / errors out. Callers treat `None` as "sysmon
    unavailable" and leave GPU snapshot fields as their defaults; a 0.0 sum
    means sysmon worked but no subtree PID holds GPU memory (CPU-only plugin
    on a GPU box).
    """
    if sysmon is None or not hasattr(sysmon, 'list_processes'):
        return None
    try:
        procs = sysmon.list_processes() or ()
    except Exception:
        return None

    tree = _worker_subtree_pids(stats)
    if not tree:
        return {'gpu_memory_mb': 0.0, 'gpu_index': None}

    total_mb: float = 0.0
    best_pid_mb: float = -1.0
    best_gpu_index: Optional[int] = None
    for proc in procs:
        pid = _proc_field(proc, 'pid')
        if pid is None or pid not in tree:
            continue
        mem = _proc_field(proc, 'gpu_memory_mb', 0.0) or 0.0
        try:
            mem = float(mem)
        except (TypeError, ValueError):
            mem = 0.0
        total_mb += mem
        if mem > best_pid_mb:
            best_pid_mb = mem
            best_gpu_index = _proc_field(proc, 'gpu_index')

    return {'gpu_memory_mb': total_mb, 'gpu_index': best_gpu_index}
