"""The tool-capability interface — the manage-the-tool half of the capability-unit fracture (pass-2 Thread 3)

Docs: https://cj-mills.github.io/cjm-plugin-systemcore/capability.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/core/capability.ipynb.

# %% auto #0
__all__ = ['RELOAD_TRIGGER', 'WORKER_ENV_TEMPLATE_PLACEHOLDERS', 'ConfigOption', 'FieldOptions', 'EnvVarSpec',
           'expand_worker_env_template', 'template_check_placeholders', 'ToolCapability', 'capability_action',
           'collect_capability_actions', 'derive_structural_surface']

# %% ../../nbs/core/capability.ipynb #f96db51b
import dataclasses
import inspect
import logging
import string
import threading
import time
from abc import ABC, abstractmethod
from contextlib import contextmanager
from typing import Any, Callable, Dict, Generator, Iterator, List, Mapping, Optional, Set

from .errors import CapabilityCancelledError, CapabilityConfigError, CapabilityInputError

# CR-4: metadata key for declarative reload triggers on config dataclass fields.
# Plugin authors annotate fields whose changes require resource release:
#
#     @dataclass
#     class WhisperConfig:
#         model: str = field(default="base", metadata={RELOAD_TRIGGER: "model"})
#         temperature: float = field(default=0.0)  # no reload needed on change
#
# Plugins then implement `_release_<trigger>()` methods (e.g. `_release_model`)
# and the substrate-provided `reconfigure_with_triggers` walks the diff between
# old and new configs, firing each affected trigger's release method.
RELOAD_TRIGGER = "reload_trigger"

_logger = logging.getLogger(__name__)

# %% ../../nbs/core/capability.ipynb #cr11dc01
@dataclasses.dataclass
class ConfigOption:
    """CR-11: one live option for a dynamic config field, with optional metadata."""
    value: Any                              # option value (e.g. "gemini-2.5-flash")
    label: str                              # display label (e.g. "Gemini 2.5 Flash")
    metadata: Dict[str, Any] = dataclasses.field(default_factory=dict)  # token limits, descriptions, ...


@dataclasses.dataclass
class FieldOptions:
    """CR-11: the live option domain for one dynamic config field.

    Kept SEPARATE from the static config_schema (which CR-8 hashes for drift
    detection). The plugin-config UI merges these live options on top of the
    static schema; folding them into the schema would make every API plugin
    perpetually 'drift'.
    """
    options: List[ConfigOption]                                            # current valid options
    constraints: Dict[str, Any] = dataclasses.field(default_factory=dict)  # derived field-constraint overrides


# %% ../../nbs/core/capability.ipynb #da9319fb
@dataclasses.dataclass
class EnvVarSpec:
    """CR-12: one entry of a plugin's spawn-time worker-environment contract.

    A plugin declares the environment variables its worker subprocess reads at
    startup via `WORKER_ENV: ClassVar[List[EnvVarSpec]]`. Worker env vars are
    FIXED AT SPAWN — changing one requires a worker RESPAWN, so the substrate
    routes such changes through `reload_capability`, never `reconfigure` (the env is
    baked into the subprocess at `Popen` and can't be mutated in-process). This
    is the lifecycle distinction from a normal config field (reconfigurable in
    place via `reconfigure`/`_release_<trigger>`).

    Two flavors share this one declaration:

      - `secret=True`  : value resolved from the `SecretStore` (masked; never
                         persisted in the config store, echoed in config_schema,
                         or logged). A secret never carries a `default` — a
                         baked-in secret is a leak.
      - `secret=False` : visible value resolved from the override chain
                         (operator override > manifest `install.env_vars` >
                         this `default`); safe to display.

    Both share one injection seam: the substrate composes the resolved
    {name: value} overlay at load time and injects it into the worker env at
    spawn (extending the existing CJM_PLUGIN_DATA_DIR / CJM_MODELS_DIR injection).
    This is "derive from behaviour, not metadata" applied to the spawn env: the
    plugin declares WHICH vars it consumes + whether each is secret/required;
    the substrate owns resolution + injection.

    `options` is a forward seam for visible vars with a finite domain (e.g. a
    device selector enumerating GPUs); unused today but reserved so the
    plugin-config UI / a future `set-env` surface isn't blocked.
    """
    name: str                              # The env var the worker reads, e.g. "GEMINI_API_KEY"
    secret: bool = False                   # True -> value resolved from the SecretStore, masked
    required: bool = False                 # Worker can't do useful work until this is satisfied
    label: str = ""                        # Display label for CLI / GUI affordances
    description: str = ""                  # Help text for CLI / GUI
    default: Optional[str] = None          # Visible vars only; secrets must leave this None
    options: Optional[List[str]] = None    # Forward seam: finite domain for a visible var (unused today)


# %% ../../nbs/core/capability.ipynb #af6757b8
# Q1-A (Track 19): EnvVarSpec.default templating — `string.Template` substitution
# with a constrained placeholder vocabulary.
#
# Why templating: 7 of 8 local-model plugins carry derived path vars
# (`HF_HOME=<CJM_MODELS_DIR>/huggingface`, `TORCH_HOME`, `NLTK_DATA`, etc.) that
# were computed at install time in each plugin's `meta.py` and baked into
# `install.env_vars` as install-machine absolute paths. Moving derivation into a
# templated `EnvVarSpec.default` lets the substrate own the resolution, keeps
# the plugin declaration portable across machines (SG-23), and removes the
# author footgun of "remember to put os.environ.setdefault before the ML import"
# (the lifecycle hazard Option B carried).
#
# Constraint: single-pass + non-recursive + strict-raise on unknown placeholder.
# A `${FOO}` whose name is not in the allowed vocabulary fails LOUDLY at
# `_resolve_worker_env` time (catchable as CapabilityConfigError, which multi-inherits
# ValueError per CR-5). The same check fires inside `cjm-ctl validate` so
# misconfigured templates surface at install/release rather than first
# `load_capability`.
#
# Allowed placeholders (the minimum viable set per the audit):
#   - ${CJM_MODELS_DIR}   — substrate-injected models directory (may be None)
#   - ${CJM_PLUGIN_DATA_DIR}     — substrate-injected data directory base
#   - ${PLUGIN_DATA_DIR}  — plugin's own data subdirectory (CJM_PLUGIN_DATA_DIR/<name>)
#   - ${PLUGIN_NAME}      — plugin name (for one-off path components like NLTK)
WORKER_ENV_TEMPLATE_PLACEHOLDERS: Set[str] = {
    "CJM_MODELS_DIR",
    "CJM_PLUGIN_DATA_DIR",
    "PLUGIN_DATA_DIR",
    "PLUGIN_NAME",
}


def expand_worker_env_template(
    template: str,                       # The raw EnvVarSpec.default value (may contain ${...} placeholders)
    placeholders: Mapping[str, Optional[str]],  # Resolved values keyed by placeholder name
    *,
    plugin_name: str = "",               # For error context ("template X on plugin Y references ...")
    var_name: str = "",                  # For error context ("on EnvVarSpec(name=Z)")
) -> str:
    """Substitute `${VAR}` placeholders in `template` using `placeholders`.
    
    Strict mode (no `safe_substitute`): unknown placeholders raise
    `CapabilityConfigError` with descriptive context. Single-pass, non-recursive —
    substituted values are taken verbatim, never re-scanned for further
    placeholders. Templates without any `${...}` syntax pass through unchanged
    (so plain static defaults work as before).
    
    The allowed placeholder vocabulary is fixed via `WORKER_ENV_TEMPLATE_PLACEHOLDERS`.
    A `${FOO}` whose name is in the vocabulary but whose RESOLVED value is None
    (e.g. `CJM_MODELS_DIR` when the operator hasn't configured one) raises
    `CapabilityConfigError` with the same shape — operators get a clear signal that
    the plugin needs a value they haven't provided, rather than a silent
    substitution of empty string into a load-bearing path.
    """
    # Fast path: nothing to substitute.
    if "$" not in template:
        return template
    # Identify placeholder names referenced in the template before substituting,
    # so we can surface a precise CapabilityConfigError for unknown names without
    # relying on string.Template's stock KeyError message.
    tmpl = string.Template(template)
    referenced: Set[str] = set()
    for match in tmpl.pattern.finditer(template):
        named = match.group("named") or match.group("braced")
        if named:
            referenced.add(named)
    # Validate against the allowed vocabulary.
    unknown = referenced - WORKER_ENV_TEMPLATE_PLACEHOLDERS
    if unknown:
        ctx = f"on plugin {plugin_name!r}" if plugin_name else ""
        if var_name:
            ctx = f"{ctx} EnvVarSpec(name={var_name!r})" if ctx else f"EnvVarSpec(name={var_name!r})"
        raise CapabilityConfigError(
            f"unknown placeholder(s) {sorted(unknown)} in worker-env default {template!r} "
            f"{ctx}; allowed: {sorted(WORKER_ENV_TEMPLATE_PLACEHOLDERS)}",
            fields_invalid=[var_name] if var_name else None,
        )
    # Resolve. A referenced-but-unresolved placeholder (allowed vocabulary,
    # value None in `placeholders`) is a configuration error from the operator
    # side, NOT a plugin author bug — distinguished error message.
    missing = [n for n in referenced if placeholders.get(n) is None]
    if missing:
        ctx = f"on plugin {plugin_name!r}" if plugin_name else ""
        if var_name:
            ctx = f"{ctx} EnvVarSpec(name={var_name!r})" if ctx else f"EnvVarSpec(name={var_name!r})"
        raise CapabilityConfigError(
            f"worker-env default {template!r} {ctx} references placeholder(s) "
            f"{sorted(missing)} but no value is configured for them "
            f"(operator must set e.g. CJM_MODELS_DIR via cjm.yaml or environment)",
            fields_invalid=[var_name] if var_name else None,
        )
    # Strict substitution. We've pre-validated unknowns + missings, so
    # substitute() can't raise KeyError; this is defense in depth.
    return tmpl.substitute({k: v for k, v in placeholders.items() if v is not None})


def template_check_placeholders(
    template: str,                       # The raw EnvVarSpec.default value
) -> Set[str]:                            # Placeholder names referenced (allowed-vocabulary-validated)
    """Return the set of placeholder names referenced by a worker-env template.
    
    Validates the vocabulary (unknown names raise CapabilityConfigError) without
    requiring a placeholder-value mapping. Useful for `cjm-ctl validate`'s
    dry-run check at install/release time — surface the bug BEFORE the plugin
    tries to spawn a worker with a malformed default.
    
    Templates without `${...}` return an empty set.
    """
    if "$" not in template:
        return set()
    tmpl = string.Template(template)
    referenced: Set[str] = set()
    for match in tmpl.pattern.finditer(template):
        named = match.group("named") or match.group("braced")
        if named:
            referenced.add(named)
    unknown = referenced - WORKER_ENV_TEMPLATE_PLACEHOLDERS
    if unknown:
        raise CapabilityConfigError(
            f"unknown placeholder(s) {sorted(unknown)} in worker-env default {template!r}; "
            f"allowed: {sorted(WORKER_ENV_TEMPLATE_PLACEHOLDERS)}",
        )
    return referenced

# %% ../../nbs/core/capability.ipynb #287e8911
class ToolCapability(ABC):
    """Tool-capability interface: manage the tool/worker — identity, lifecycle,
    config, cancellation, observability (pass-2 Thread 3 fracture).

    The task channel is NOT part of this surface: `execute` left the abstract
    set when the capability-unit fracture split tool capabilities from task
    adapters. Typed task contracts live on adapters (`core.adapter` + the
    per-task `cjm-<task>-adapter-interface` libraries). Fused-era plugins (the
    pre-Option-C 12) still define `execute` themselves and their domain ABCs
    still declare it abstract — they keep working unchanged through the
    class-identical `ToolCapability` alias in `core.interface` until the
    Option C migration cascade splits them.

    CR-4 extended this surface with: prefetch hook (SG-19), made cleanup optional
    (SG-43), reconfigure split + RELOAD_TRIGGER declarative-helper (lifecycle
    hook split), and cooperative-cancellation primitives (SG-16 — flag + callback
    + context manager).

    Abstract methods: `name`, `version`, `initialize`, `get_config_schema`,
    `get_current_config`. Concrete defaults (overridable): `execute_stream`
    (transitional — see method), `cleanup`, `prefetch`, `reconfigure`,
    `cancel`, `check_cancel`, `register_cancel_callback`, `cancel_signal_to`,
    `report_progress`, `report_usage`, `fields_that_changed`,
    `reconfigure_with_triggers`, `on_disable`, `on_enable`.
    """

    # CR-4: cooperative-cancellation flag. Class-level default so subclasses
    # don't have to remember to initialize it in __init__; setting on an
    # instance creates an instance attribute that shadows the class default.
    # Reset by the substrate's worker /execute wrapper before each call so
    # stale state from a previous cancellation doesn't leak forward.
    _cancel_requested: bool = False

    @property
    @abstractmethod
    def name(self) -> str: # Unique identifier for this plugin
        """Unique plugin identifier."""
        ...

    @property
    @abstractmethod
    def version(self) -> str: # Semantic version string (e.g., "1.0.0")
        """Plugin version."""
        ...

    @abstractmethod
    def initialize(
        self,
        config: Optional[Dict[str, Any]] = None # Configuration dictionary
    ) -> None:
        """Initialize or re-configure the plugin.
        
        CR-4: this is "first-time setup" — called once after construction with
        the initial config. Substrate uses `reconfigure(old, new)` for delta
        updates afterwards. Plugins predating CR-4 see no behavior change since
        the default `reconfigure()` body delegates to `reconfigure_with_triggers`
        which is a no-op unless the plugin opts in via RELOAD_TRIGGER metadata.
        """
        ...

    def execute_stream(
        self,
        *args,
        **kwargs
    ) -> Generator[Any, None, None]: # Yields partial results
        """Stream execution results chunk by chunk.

        TRANSITIONAL(option-c-cascade): streaming is substrate/composition-
        supplied under the pass-2 fracture (off both interfaces); the default
        stays here only because fused-era plugins rely on it (it calls the
        plugin's own `execute`, which a split tool capability does not have).
        Relocates when CR-17 adapter routing lands (execution stage 4).
        """
        # Fused-era default: yield single result from execute().
        yield self.execute(*args, **kwargs)

    @abstractmethod
    def get_config_schema(self) -> Dict[str, Any]: # JSON Schema for configuration
        """Return JSON Schema describing the plugin's configuration options."""
        ...

    @abstractmethod
    def get_current_config(self) -> Dict[str, Any]: # Current configuration values
        """Return the current configuration state as a dictionary."""
        ...

    def get_config_options(self) -> Dict[str, "FieldOptions"]:
        """CR-11: live option domains for dynamic config fields, keyed by field name.

        Optional. Default: {} (fully static plugins). For fields whose valid
        domain is determined at runtime (e.g. an API model list), return a
        `FieldOptions` carrying current `ConfigOption` values + per-option
        metadata (token limits, etc.) + optional derived constraints. Runs in
        the worker subprocess (has the plugin's deps + credentials).

        Kept SEPARATE from get_config_schema(): the schema is static + hashed for
        CR-8 drift detection; these options are the live, un-hashed companion the
        plugin-config UI merges on top. A fetch failure should raise a typed CR-5
        error; the substrate's CapabilityManager.get_config_options accessor degrades
        to {} so the UI can fall back to the static schema.
        """
        return {}

    def cleanup(self) -> None:
        """Clean up resources when plugin is unloaded.
        
        CR-4: made optional (SG-43 closure). Was `@abstractmethod` before; every
        audited plugin overrode it with a near-no-op, so the default is now a
        no-op and plugin authors override only when they have non-trivial
        teardown (file handles, GPU memory, database connections). The
        substrate's worker /cleanup endpoint calls this regardless.
        """
        pass

    def prefetch(self) -> None:
        """Acquire heavy resources eagerly without invoking execute().
        
        CR-4 (SG-19): default no-op. Plugin authors override when downstream
        callers benefit from eager acquisition — typically transcription /
        inference plugins that lazy-download models on first execute. The
        substrate's prefetch_plugin(name) API + worker /prefetch endpoint
        invoke this. Should be idempotent (safe to call multiple times) since
        the substrate may pre-warm at load time AND on operator request.
        """
        pass

    def reconfigure(
        self,
        old_config: Optional[Dict[str, Any]],  # Previous configuration values
        new_config: Optional[Dict[str, Any]],  # New configuration values to apply
    ) -> None:
        """Apply a configuration change without re-running full initialize().
        
        CR-4 completion (2026-05-25): reconfigure is the substrate's canonical
        delta path - `CapabilityManager.update_capability_config` routes here, NOT through
        a bare `initialize(new_config)`. It fires `_release_<trigger>` releases for
        changed RELOAD_TRIGGER fields, then re-applies config (see body below).
        
        Distinction from initialize(): initialize sets up persistent state once
        after construction; reconfigure applies delta updates and is the
        canonical entry point for hot-reload via the substrate's
        update_capability_config path.
        """
        self.reconfigure_with_triggers(old_config or {}, new_config or {})
        # CR-4 completion: re-apply config + run config-derived setup. Plugins
        # that factor config into `_apply_config(config)` get the clean
        # init-once / reconfigure-delta split; others fall back to a full
        # `initialize(new_config)` (idempotent; retained manual diff-and-reload
        # blocks are harmless - `_release_*` guards make the second release a no-op).
        apply_config = getattr(self, "_apply_config", None)
        if callable(apply_config):
            apply_config(new_config or {})
        else:
            self.initialize(new_config or {})

    def fields_that_changed(
        self,
        old: Dict[str, Any],  # Previous config snapshot
        new: Dict[str, Any],  # Proposed new config snapshot
    ) -> Set[str]:  # Field names whose values differ between old and new
        """Return the set of field names whose values differ between old and new.
        
        Includes fields present in only one dict (treated as a change to/from
        the implicit None). Equality is structural via `!=`; nested dicts /
        lists compare by value, not identity. Hashable-vs-unhashable values
        compare correctly because we never put them in a set themselves.
        """
        all_keys = set(old) | set(new)
        return {k for k in all_keys if old.get(k) != new.get(k)}

    def reconfigure_with_triggers(
        self,
        old_config: Dict[str, Any],  # Previous configuration values
        new_config: Dict[str, Any],  # New configuration values being applied
    ) -> None:
        """CR-4 helper: walk RELOAD_TRIGGER metadata + fire `_release_<trigger>` methods.
        
        Resolution sequence:
        
          1. Find the plugin's `config_class` attribute (a dataclass). Absent
             means the plugin hasn't opted into the declarative pattern; the
             helper returns silently.
          2. Compute the diff between `old_config` and `new_config` via
             `fields_that_changed`.
          3. For each changed field, read its `RELOAD_TRIGGER` metadata key
             (if any) and accumulate the trigger names into a set (de-duping
             when multiple fields share a trigger).
          4. For each trigger, call `self._release_<trigger>()` if it exists
             on the instance.
        
        Plugin authors opt in by:
        
          - Setting `config_class = MyConfigDataclass` as a class attribute.
          - Annotating field metadata with `{RELOAD_TRIGGER: "model"}` etc.
          - Implementing matching `_release_model(self)` instance methods.
        
        Plugins WITHOUT config_class or RELOAD_TRIGGER metadata land here as a
        no-op — safe default for the SG-T3tr migration window where the
        cascade hasn't yet adopted the declarative pattern everywhere.
        """
        config_class = getattr(type(self), "config_class", None)
        if config_class is None or not dataclasses.is_dataclass(config_class):
            return
        changed = self.fields_that_changed(old_config, new_config)
        if not changed:
            return
        triggers_to_fire: Set[str] = set()
        for f in dataclasses.fields(config_class):
            if f.name not in changed:
                continue
            trigger = f.metadata.get(RELOAD_TRIGGER) if hasattr(f, "metadata") else None
            if trigger:
                triggers_to_fire.add(trigger)
        for trigger in triggers_to_fire:
            release_method = getattr(self, f"_release_{trigger}", None)
            if callable(release_method):
                try:
                    release_method()
                except Exception as e:
                    # A misbehaving _release method must NOT prevent the rest
                    # from firing — heavy-resource teardown is best-effort.
                    _logger.warning(
                        "_release_%s() raised on %r; continuing with remaining triggers: %s",
                        trigger, getattr(self, "name", type(self).__name__), e,
                    )

    def cancel(self) -> None:
        """Request cooperative cancellation of the current execute() call.
        
        CR-4: default sets the substrate-tracked `_cancel_requested` flag and
        fires any callbacks registered via `register_cancel_callback`.
        
        Plugin authors who need extra teardown logic (signaling a subprocess,
        closing a network connection) override `cancel()` and SHOULD call
        `super().cancel()` to preserve the flag-setting + callback-fire
        behavior. The plugin's `execute()` polls via `check_cancel()` at safe
        interruption points and unwinds when it raises `CapabilityCancelledError`.
        """
        self._cancel_requested = True
        for cb in list(getattr(self, "_cancel_callbacks", ())):
            try:
                cb()
            except Exception as e:
                # Cancellation callbacks are best-effort; a misbehaving one
                # must not stop subsequent callbacks from firing.
                _logger.warning(
                    "cancel callback raised on %r: %s",
                    getattr(self, "name", type(self).__name__), e,
                )

    def check_cancel(self) -> None:
        """Raise `CapabilityCancelledError` if cancellation has been requested.
        
        CR-4 (SG-16 polling primitive): plugin authors call this at safe
        interruption points inside `execute()`. The substrate sets the flag via
        `cancel()` (typically driven by an operator's "Cancel" button); the
        next `check_cancel` call surfaces the cancellation as a typed exception
        that unwinds execute() cleanly.
        
        The substrate's worker /execute wrapper resets the flag before each
        call so cancellation doesn't leak from one job into the next.
        """
        if self._cancel_requested:
            raise CapabilityCancelledError(self.name)

    def register_cancel_callback(
        self,
        callback: Callable[[], None],  # Called when cancel() fires
    ) -> None:
        """Register a callback that fires when cancel() is called.
        
        CR-4 (SG-16 callback primitive): for plugins that can't easily insert
        polling at strategic points (e.g., a plugin wrapping a blocking C
        extension). Callbacks should be non-blocking and idempotent. Multiple
        callbacks can be registered; all fire in registration order when
        cancel() is invoked. A misbehaving callback that raises is logged
        and skipped — the remaining callbacks still fire.
        """
        if not hasattr(self, "_cancel_callbacks"):
            self._cancel_callbacks: List[Callable[[], None]] = []
        self._cancel_callbacks.append(callback)

    @contextmanager
    def cancel_signal_to(
        self,
        callback: Callable[[], None],  # Cancellation callback scoped to the with-block
    ) -> Generator[None, None, None]:
        """Context manager registering `callback` for the duration of the with-block.
        
        Useful for binding cancellation to a finite-scope resource (a subprocess,
        a network request, a temporary file handle) without needing to
        deregister manually. Pairs with `register_cancel_callback` for cases
        where lifetime is tied to a `try:`/`finally:` block.
        
        Example:
        
            def execute(self, *args, **kwargs):
                proc = subprocess.Popen(...)
                with self.cancel_signal_to(lambda: proc.terminate()):
                    return proc.wait()
        """
        self.register_cancel_callback(callback)
        try:
            yield
        finally:
            if hasattr(self, "_cancel_callbacks"):
                try:
                    self._cancel_callbacks.remove(callback)
                except ValueError:
                    pass  # Already removed (e.g. by an aliased call); silent OK.

    def on_disable(self) -> None:
        """CR-2: signal that the substrate has marked this plugin as disabled.
        
        Worker stays alive; plugin can release heavy resources here (e.g., free
        GPU memory, close model files). The substrate fires this hook AFTER any
        in-flight job for this plugin finishes — see CapabilityManager.disable_capability
        deferred-hook semantics. Default: no-op; plugins opt in by overriding.
        """
        pass

    def on_enable(self) -> None:
        """CR-2: signal that the substrate has marked this plugin as re-enabled.
        
        Plugin can eagerly re-acquire heavy resources here, or rely on lazy
        re-acquisition via the next execute() call (substrate doesn't prefer
        one strategy over the other). Default: no-op; plugins opt in by overriding.
        """
        pass

    def report_progress(
        self,
        progress: float, # 0.0 to 1.0, or -1.0 for indeterminate
        message: str = "" # Descriptive status message
    ) -> None:
        """Report execution progress. Call during execute() to update status."""
        # Default: store in instance variables for worker to poll
        self._progress = progress
        self._status_message = message

    def report_usage(
        self,
        usage: Dict[str, float],  # Measured usage for this execute, keyed by plugin-defined unit name
    ) -> None:
        """SG-54: report measured API/service usage for the current execute() call.

        Unit-agnostic by design — the plugin (which holds the API response)
        supplies whatever unit names it measures: {"input_tokens": .., "output_tokens": ..}
        for an LLM, {"pages": ..} for OCR, {"characters": ..} for TTS,
        {"credits"/"requests"/"minutes": ..} for others. The substrate stores +
        accumulates per unit name WITHOUT interpreting them (summed across runs in
        the empirical store's api_usage_totals). Pricing is deliberately NOT here
        (volatile, per-service, often not API-accessible) — a consumer-side rate
        table turns raw units into cost. "Derive from behaviour": the plugin
        MEASURES actual usage from the response; the substrate aggregates.

        Stored on `self._last_api_usage`; the worker exposes it via /stats and the
        substrate folds it into the post-execute ResourceSample. The worker resets
        it before each execute so a failed/usage-less call can't inherit stale
        usage. Default: store-only (parallel to report_progress).
        """
        self._last_api_usage = dict(usage)

# %% ../../nbs/core/capability.ipynb #548ddb70
# Q2 (Track 19 companion): heartbeat context manager + thread-safe report_progress.
#
# The substrate's prefetch stall-detector (Session A 2026-05-27) SIGTERMs a
# worker if the (progress, message) tuple stays unchanged for
# `SubstrateConfig.prefetch_stall_threshold_seconds`. Plugins with quiet
# lifecycle ops (HF Hub `from_pretrained`, `torch.hub.load_state_dict_from_url`,
# whisper's urllib download) are silently at risk: their _load_model() blocks for
# 60+ seconds without emitting progress updates.
#
# Voxtral-vLLM is the first adopter (single-threaded, plugin-owned poll loop —
# the heartbeat is "call report_progress on every iteration of my loop"). The 5
# remaining model-loading plugins (Whisper / Voxtral-HF / Qwen3-FA / Demucs /
# LavaSR) have a different shape: ONE blocking call inside third-party code
# they don't own. That shape needs a BACKGROUND thread emitting heartbeats
# while the main thread blocks in `from_pretrained`.
#
# This cell ships TWO sibling primitives:
#
#   - `report_progress` thread-safety upgrade: report_progress is now safe to
#     call from any thread (the heartbeat thread + the plugin's main thread
#     may both call it). Single lazy-init lock per plugin instance; single-
#     threaded callers (the existing majority) get a `getattr is None` fast
#     path with zero lock overhead until the first heartbeat() call.
#
#   - `heartbeat(phase, *, interval, progress)` context manager: spawns a
#     daemon thread that re-writes `_status_message` every `interval` seconds
#     with `<base> ({elapsed:.1f}s)`. The thread NEVER touches `_progress` or
#     `_status_message_base` — those stay owned by explicit `report_progress`
#     calls. So the plugin can still drive real progress fractions during the
#     block; the heartbeat just guarantees the (progress, message) tuple
#     advances even when nothing else is happening.
#
# Per Q2 Option C: this is opt-in convenience on top of the existing
# report_progress seam, NOT a forced shape. Voxtral-vLLM's plugin-owned loop
# stays as-is. 5 model-loading plugins adopt this CM in Phase 3.
def _report_progress_threadsafe(
    self,
    progress: float,  # 0.0 to 1.0, or -1.0 for indeterminate
    message: str = "",  # Descriptive status message
) -> None:
    """Thread-safe report_progress — replaces ToolCapability.report_progress.
    
    Writes `_progress` + `_status_message_base` + `_status_message` under the
    plugin's `_progress_lock` if one exists (lazy-init by `heartbeat()` before
    spawning its thread). When no lock exists yet — the single-threaded common
    case before any heartbeat() call — the writes happen without lock overhead.
    
    The heartbeat thread reads `_status_message_base` (NOT `_status_message`)
    so heartbeat-amended messages don't accumulate elapsed-time suffixes when
    `report_progress` is called concurrently. The plugin's call overwrites both
    fields atomically; the next heartbeat tick reads the new base.
    """
    lock = getattr(self, "_progress_lock", None)
    if lock is None:
        # Fast path for single-threaded callers (the majority — Voxtral-vLLM
        # and any plugin that hasn't entered a heartbeat() block). No lock
        # overhead. heartbeat() initializes the lock before spawning its
        # thread, so concurrent multi-thread access always sees a lock.
        self._progress = progress
        self._status_message_base = message
        self._status_message = message
        return
    with lock:
        self._progress = progress
        self._status_message_base = message
        self._status_message = message


ToolCapability.report_progress = _report_progress_threadsafe


@contextmanager
def _heartbeat(
    self,
    phase: str,                    # Phase label embedded in the heartbeat message
    *,
    interval: float = 0.5,         # Seconds between heartbeats (substrate stalls at 60s default)
    progress: Optional[float] = None,  # Optional initial progress; None preserves current
) -> Iterator[None]:
    """Heartbeat context manager — spawn a daemon thread that advances the
    (progress, message) tuple every `interval` seconds, defeating the
    substrate's prefetch stall detection during silent blocking calls.
    
    Usage:
    
        def prefetch(self):
            with self.heartbeat("loading whisper model"):
                self._load_model()  # Blocking; HF Hub download / from_pretrained
    
    Behavior:
    
    - At entry: writes `(progress, phase)` to set the initial state. If
      `progress` is None, preserves whatever `self._progress` already holds
      (defaulting to 0.5 indeterminate if never set).
    - During the block: a daemon thread emits an updated `_status_message =
      "<base> ({elapsed:.1f}s)"` every `interval` seconds. The thread reads
      `_status_message_base` (set by `report_progress`) for the base, so an
      explicit `report_progress(0.3, "downloading weights")` from inside the
      block makes the next heartbeat tick display "downloading weights (Xs)".
    - At exit: signals the thread to stop, joins with timeout (the thread is
      daemon so cleanup is best-effort but reliable). The plugin's final
      `_status_message` state is left as the last heartbeat-amended value;
      callers wanting a clean "completed" state should call
      `report_progress(1.0, "done")` after the with-block.
    
    Thread safety: relies on the upgraded thread-safe `report_progress`
    (loaded by this same cell). The lock is lazy-initialized HERE — before
    spawning the heartbeat thread — so concurrent main-thread + heartbeat-
    thread calls always see a lock.
    
    Cancellation: the heartbeat thread checks `stop_event` between sleeps
    and exits cleanly. If the with-block raises, the `finally` clause still
    fires `stop_event.set()`, so the thread won't leak.
    """
    # Lazy-init the lock BEFORE spawning the thread. This is the single point
    # where a write-write race is possible if multiple heartbeat() calls
    # nested or interleaved at the millisecond level — in practice plugins
    # never call heartbeat() reentrantly, and the GIL makes the dict write
    # atomic anyway. Belt-and-suspenders: if the attribute already exists
    # (e.g. from a previous heartbeat() call in the same plugin lifetime),
    # we reuse it.
    if getattr(self, "_progress_lock", None) is None:
        self._progress_lock = threading.Lock()

    # Initial state: explicit progress argument > current progress > 0.5
    # (indeterminate). The phase label becomes the message base; the thread
    # will append elapsed time on each tick.
    initial_progress = progress if progress is not None else getattr(self, "_progress", 0.5)
    self.report_progress(initial_progress, phase)

    start_time = time.time()
    stop_event = threading.Event()

    def _heartbeat_loop() -> None:
        # The thread NEVER touches _progress or _status_message_base — those
        # stay owned by explicit report_progress calls. The thread only refreshes
        # _status_message with the elapsed-time suffix. This means the substrate
        # sees the tuple advance (message changes every tick); the plugin's
        # explicit progress fractions and base messages propagate cleanly.
        while not stop_event.is_set():
            elapsed = time.time() - start_time
            with self._progress_lock:
                base = getattr(self, "_status_message_base", phase) or phase
                self._status_message = f"{base} ({elapsed:.1f}s)" if base else f"({elapsed:.1f}s)"
            # Wait on the event with a timeout so we can be interrupted between
            # ticks if the with-block exits early.
            stop_event.wait(interval)

    thread = threading.Thread(target=_heartbeat_loop, daemon=True, name=f"heartbeat-{phase[:32]}")
    thread.start()
    try:
        yield
    finally:
        stop_event.set()
        # Daemon thread; join with timeout so a misbehaving thread can't block
        # the with-block from exiting. interval*2 gives the thread one full
        # cycle to notice the event; minimum 1.0s for very tight intervals.
        thread.join(timeout=max(interval * 2, 1.0))


ToolCapability.heartbeat = _heartbeat

# %% ../../nbs/core/capability.ipynb #540be780
def capability_action(
    action_name: str  # Public action name the decorated method handles
) -> Callable[[Callable], Callable]:  # Decorator
    """Marker decorator tagging a plugin method as the handler for `action_name`.
    
    Sets `func._capability_action = action_name`. Plugin authors with dispatcher-style
    `execute(action, **kwargs)` use `collect_capability_actions(cls)` to derive their
    `supported_actions` set from these markers rather than maintaining a separate
    list. The decorator does not change call semantics — the wrapped function is
    returned unchanged.
    """
    def decorator(func: Callable) -> Callable:
        func._capability_action = action_name
        return func
    return decorator


def collect_capability_actions(
    cls: type  # Class (or subclass) to scan for @capability_action-tagged methods
) -> Set[str]:  # Set of action names handled by `cls` (including inherited)
    """Collect action names from `@capability_action`-decorated methods on `cls`.
    
    Walks the class's MRO so subclasses inherit action handlers from base
    classes automatically. The returned set is suitable for
    `supported_actions: ClassVar[Set[str]] = collect_capability_actions(MyPlugin)`
    once the plugin class body has been defined.
    """
    actions: Set[str] = set()
    for ancestor in cls.__mro__:
        for attr in vars(ancestor).values():
            tag = getattr(attr, "_capability_action", None)
            if isinstance(tag, str):
                actions.add(tag)
    return actions

# %% ../../nbs/core/capability.ipynb #91b2cd38
def _dispatch_to_action(
    self,
    action: str,  # Action name to dispatch (matched against @capability_action tags)
    **kwargs,     # Forwarded verbatim to the resolved handler
) -> Any:         # Whatever the handler returns
    """T28: dispatch `action` to its `@capability_action`-tagged handler.

    Walks the instance's MRO for a method tagged `_capability_action == action`
    (the SAME markers `collect_capability_actions` / `supported_actions` are built
    from) and calls it as `handler(self, **kwargs)`. Unknown actions raise the
    typed `CapabilityInputError(fields_invalid=["action"])` (CR-5) — identical
    behaviour to the hand-rolled dispatchers this replaces.

    Dispatcher-style plugins (MediaProcessing / Graph / Text) collapse their
    `execute` to a one-liner instead of reimplementing the MRO walk in every
    plugin (the 5x copy SG-44 + this helper retire):

        @capability_action("separate_vocals")
        def _separate_vocals(self, **kwargs): ...

        supported_actions = collect_capability_actions(MyPlugin)

        def execute(self, action="separate_vocals", **kwargs):
            return self.dispatch_to_action(action, **kwargs)
    """
    for klass in type(self).__mro__:
        for attr in vars(klass).values():
            if getattr(attr, "_capability_action", None) == action:
                return attr(self, **kwargs)
    raise CapabilityInputError(
        f"Unknown action: {action}", fields_invalid=["action"],
    )


ToolCapability.dispatch_to_action = _dispatch_to_action

# %% ../../nbs/core/capability.ipynb #9342f856-f07e-4e18-b016-4f089a50c4c4
class _CR4MinimalCapability(ToolCapability):
    """Concrete plugin satisfying abstracts; relies on CR-4 default cleanup()."""
    @property
    def name(self) -> str: return "cr4-minimal"
    @property
    def version(self) -> str: return "0.0.0"
    def initialize(self, config=None): self._cfg = dict(config or {})
    def execute(self, *args, **kwargs): return None
    def get_config_schema(self) -> Dict[str, Any]: return {}
    def get_current_config(self) -> Dict[str, Any]: return dict(getattr(self, "_cfg", {}))

# %% ../../nbs/core/capability.ipynb #76176c92
def derive_structural_surface(
    cls: type,  # The capability class to introspect
) -> Dict[str, Any]:  # {"methods": [...], "properties": [...], "attributes": [...]}
    """Record a capability class's structural surface by pure self-introspection.

    The FULL public surface is recorded, inherited members included —
    the surface is what adapter protocols match against, and protocol
    members may name inherited methods. Deterministic (name-sorted) so
    the canonical-JSON witness hash is stable across runs.

    Classification: `property` → properties (names only); functions
    (static/class methods unwrapped) → methods with `str(inspect.signature)`
    + the parameter NAME list `params` (self excluded — the CR-17 pt 2
    surface matcher's input; stage 4);
    everything else public → attributes with the value's type name
    (config_class, supported_actions, WORKER_ENV, ...).
    """
    methods: List[Dict[str, str]] = []
    properties: List[str] = []
    attributes: List[Dict[str, str]] = []
    for name in sorted(dir(cls)):
        if name.startswith("_"):
            continue
        attr = inspect.getattr_static(cls, name)
        if isinstance(attr, property):
            properties.append(name)
            continue
        if isinstance(attr, (staticmethod, classmethod)):
            attr = attr.__func__
        if inspect.isfunction(attr):
            try:
                signature = inspect.signature(attr)
                sig = str(signature)
                params = [p for p in signature.parameters if p != "self"]
            except (ValueError, TypeError):
                sig, params = "(...)", []
            methods.append({"name": name, "signature": sig, "params": params})
        else:
            attributes.append({"name": name, "type": type(attr).__name__})
    return {"methods": methods, "properties": properties, "attributes": attributes}
