"""Persistent store for empirically-observed resource usage per (instance_id, config_hash) pair. CR-7's data foundation — `record_sample` is called from `CapabilityManager.execute_capability*` finally blocks; aggregates feed eviction-candidate selection + future UI hints + cost-aware retry decisions.

Docs: https://cj-mills.github.io/cjm-plugin-systemcore/empirical_store.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/core/empirical_store.ipynb.

# %% auto #0
__all__ = ['compute_config_hash', 'ResourceSample', 'EmpiricalResourceRecord', 'EmpiricalResourceStore',
           'LocalEmpiricalResourceStore']

# %% ../../nbs/core/empirical_store.ipynb #exports
import json
import sqlite3
from contextlib import contextmanager
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, Iterator, List, Optional, Protocol, runtime_checkable

import logging
_logger = logging.getLogger(__name__)

from ..utils.hashing import hash_dict_canonical

# %% ../../nbs/core/empirical_store.ipynb #compute-config-hash
def compute_config_hash(
    config: Optional[Dict[str, Any]],  # Plugin's effective config dict (or None / empty)
) -> str:  # Hash string in "algo:hexdigest" format
    """CR-7: hash a plugin instance's effective config for empirical-record keying.
    
    Same canonicalization as CR-8's `compute_config_schema_hash` — sorted keys,
    no whitespace, `"sha256:hex"` shape. None / empty configs hash deterministically
    to the canonical-empty value so plugins with no config still get a single
    record per instance rather than scattering across hash-of-None edge cases.
    """
    return hash_dict_canonical(config)

# %% ../../nbs/core/empirical_store.ipynb #resource-sample
@dataclass(frozen=True)
class ResourceSample:
    """Single observation captured after an execute call completes.
    
    Frozen — substrate aggregates online via Welford's algorithm; no need to
    keep raw samples around. `observed_at` is tz-aware per the CR-5 convention.
    """
    cpu_percent: float  # Worker CPU% at end-of-execute (proxy for peak)
    memory_mb_peak: float  # Worker RSS in MB at end-of-execute (proxy for peak)
    gpu_memory_mb_peak: float  # Worker GPU memory in MB at end-of-execute (0.0 if no GPU)
    duration_seconds: float  # Wall-clock execute duration
    success: bool  # True if execute returned normally; False if raised
    observed_at: datetime  # tz-aware datetime — when the sample was captured
    api_usage: Optional[Dict[str, float]] = None  # SG-54: unit-agnostic measured usage {unit_name: amount}; None for compute-only plugins

# %% ../../nbs/core/empirical_store.ipynb #resource-record
@dataclass
class EmpiricalResourceRecord:
    """Aggregated empirical resource profile for a (instance_id, config_hash) pair."""
    instance_id: str  # CapabilityInstance.instance_id (CR-10 multi-instance aware)
    capability_name: str  # Convenience: CapabilityInstance.capability_name; derivable but cheap to denormalize
    config_hash: str  # compute_config_hash(inst.config) at sample time
    sample_count: int  # Number of ResourceSamples folded into this record
    cpu_percent_mean: float  # Welford running mean of cpu_percent
    memory_mb_peak_max: float  # max(sample.memory_mb_peak over all samples) — worst observed
    memory_mb_peak_mean: float  # Welford running mean of sample.memory_mb_peak
    gpu_memory_mb_peak_max: float  # max(sample.gpu_memory_mb_peak over all samples)
    gpu_memory_mb_peak_mean: float  # Welford running mean of sample.gpu_memory_mb_peak
    duration_seconds_mean: float  # Welford running mean of sample.duration_seconds
    success_rate: float  # success_count / sample_count
    last_observed: datetime  # tz-aware; tracks most recent ResourceSample.observed_at
    api_usage_totals: Dict[str, float] = field(default_factory=dict)  # SG-54: cumulative per-unit usage summed across runs (tokens/credits/pages/...); {} for compute-only plugins

# %% ../../nbs/core/empirical_store.ipynb #store-protocol
@runtime_checkable
class EmpiricalResourceStore(Protocol):
    """Protocol for persisting empirically-observed resource usage.
    
    Implementations aggregate online (Welford for means, max-of-peaks for memory).
    No raw-sample retention required — v1 is one row per (instance_id, config_hash)
    pair with running aggregates. A future implementation can add a samples table
    if time-series queries become necessary.
    """
    
    def record_sample(
        self,
        instance_id: str,
        capability_name: str,
        config_hash: str,
        sample: ResourceSample,
    ) -> None:
        """Fold a sample into the running aggregate. Creates a new record on first call."""
        ...
    
    def get_record(
        self,
        instance_id: str,
        config_hash: str,
    ) -> Optional[EmpiricalResourceRecord]:
        """Fetch the aggregated record for (instance_id, config_hash), or None."""
        ...
    
    def list_records(
        self,
        capability_name: Optional[str] = None,
    ) -> List[EmpiricalResourceRecord]:
        """List all records, optionally filtered to a single capability_name."""
        ...
    
    def delete_record(
        self,
        instance_id: str,
        config_hash: str,
    ) -> bool:
        """Remove a record. Returns True if a row was deleted."""
        ...

# %% ../../nbs/core/empirical_store.ipynb #imports-fastcore-patch-aa3877
from fastcore.basics import patch


# %% ../../nbs/core/empirical_store.ipynb #local-impl
_SCHEMA = """
CREATE TABLE IF NOT EXISTS empirical_resources (
    instance_id TEXT NOT NULL,
    capability_name TEXT NOT NULL,
    config_hash TEXT NOT NULL,
    sample_count INTEGER NOT NULL DEFAULT 0,
    success_count INTEGER NOT NULL DEFAULT 0,
    cpu_percent_mean REAL NOT NULL DEFAULT 0.0,
    memory_mb_peak_max REAL NOT NULL DEFAULT 0.0,
    memory_mb_peak_mean REAL NOT NULL DEFAULT 0.0,
    gpu_memory_mb_peak_max REAL NOT NULL DEFAULT 0.0,
    gpu_memory_mb_peak_mean REAL NOT NULL DEFAULT 0.0,
    duration_seconds_mean REAL NOT NULL DEFAULT 0.0,
    last_observed TEXT NOT NULL,
    api_usage_totals TEXT NOT NULL DEFAULT '{}',
    PRIMARY KEY (instance_id, config_hash)
)
"""


def _default_db_path() -> Path:
    """Default SQLite location: `~/.cjm/empirical_resources.db`.
    
    Hosts using per-project `data_dir` (the intended pattern per CR-8 cascade_manifests
    docs) override this by passing `db_path=cfg.data_dir / "empirical_resources.db"`
    when constructing the store. CapabilityManager's lazy-init does this automatically.
    """
    return Path.home() / ".cjm" / "empirical_resources.db"


class LocalEmpiricalResourceStore:
    """SQLite-backed default implementation of `EmpiricalResourceStore`.
    
    Online Welford aggregation for means; max-of-peaks for memory metrics.
    success_rate computed at read time from `success_count / sample_count`.
    DB + schema created lazily on first write.
    """
    
    def __init__(self, db_path: Optional[Path] = None):
        """Initialize the store. `db_path=None` uses `~/.cjm/empirical_resources.db`."""
        self.db_path = Path(db_path) if db_path is not None else _default_db_path()
    
    
    
    
    
    
    @staticmethod
    def _row_to_record(row) -> EmpiricalResourceRecord:
        """Convert a SQLite row tuple to a typed EmpiricalResourceRecord.
        
        success_rate computed at read time. last_observed parsed back to tz-aware
        datetime (substrate-side records always serialize via isoformat()).
        """
        (instance_id, capability_name, config_hash, sample_count, success_count,
         cpu_mean, mem_max, mem_mean, gpu_max, gpu_mean,
         dur_mean, last_observed_str, api_usage_totals_json) = row
        try:
            api_usage_totals = json.loads(api_usage_totals_json) if api_usage_totals_json else {}
        except (TypeError, ValueError):
            api_usage_totals = {}
        success_rate = (success_count / sample_count) if sample_count > 0 else 0.0
        try:
            last_observed = datetime.fromisoformat(last_observed_str)
        except (TypeError, ValueError):
            last_observed = datetime.now(timezone.utc)
        return EmpiricalResourceRecord(
            instance_id=instance_id,
            capability_name=capability_name,
            config_hash=config_hash,
            sample_count=int(sample_count),
            cpu_percent_mean=float(cpu_mean),
            memory_mb_peak_max=float(mem_max),
            memory_mb_peak_mean=float(mem_mean),
            gpu_memory_mb_peak_max=float(gpu_max),
            gpu_memory_mb_peak_mean=float(gpu_mean),
            duration_seconds_mean=float(dur_mean),
            success_rate=success_rate,
            last_observed=last_observed,
            api_usage_totals=api_usage_totals,
        )

# %% ../../nbs/core/empirical_store.ipynb #m-conn
@patch
@contextmanager
def _conn(self:LocalEmpiricalResourceStore) -> Iterator[sqlite3.Connection]:
    """Open a connection, creating parent dirs + schema on demand."""
    self.db_path.parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(self.db_path)
    try:
        conn.execute(_SCHEMA)
        # SG-54: in-place migration for DBs created before api_usage_totals.
        cols = {r[1] for r in conn.execute("PRAGMA table_info(empirical_resources)").fetchall()}
        if "api_usage_totals" not in cols:
            conn.execute("ALTER TABLE empirical_resources ADD COLUMN api_usage_totals TEXT NOT NULL DEFAULT '{}'")
        conn.commit()
        yield conn
    finally:
        conn.close()

# %% ../../nbs/core/empirical_store.ipynb #m-record-sample
@patch
def record_sample(
    self:LocalEmpiricalResourceStore,
    instance_id: str,  # CapabilityInstance.instance_id
    capability_name: str,  # CapabilityInstance.capability_name (denormalized for filtering)
    config_hash: str,  # compute_config_hash(inst.config)
    sample: ResourceSample,  # One observation
) -> None:
    """Fold a sample into the running aggregate. Creates a new row on first call.

    Welford update for each mean. Max-of-peaks for memory metrics.
    success_count incremented by 1 if sample.success else 0.
    """
    with self._conn() as conn:
        row = conn.execute(
            "SELECT sample_count, success_count, cpu_percent_mean, "
            "memory_mb_peak_max, memory_mb_peak_mean, "
            "gpu_memory_mb_peak_max, gpu_memory_mb_peak_mean, "
            "duration_seconds_mean, api_usage_totals "
            "FROM empirical_resources WHERE instance_id = ? AND config_hash = ?",
            (instance_id, config_hash),
        ).fetchone()

        success_delta = 1 if sample.success else 0
        if row is None:
            # First sample for this (instance_id, config_hash) pair.
            n = 1
            success_count = success_delta
            cpu_mean = sample.cpu_percent
            mem_mean = sample.memory_mb_peak
            gpu_mean = sample.gpu_memory_mb_peak
            dur_mean = sample.duration_seconds
            mem_max = sample.memory_mb_peak
            gpu_max = sample.gpu_memory_mb_peak
            usage_totals = {k: float(v) for k, v in (sample.api_usage or {}).items()}
        else:
            (old_n, old_success_count, old_cpu_mean,
             old_mem_max, old_mem_mean,
             old_gpu_max, old_gpu_mean,
             old_dur_mean, old_usage_totals_json) = row
            n = old_n + 1
            success_count = old_success_count + success_delta
            # Welford running-mean update: mean_n = mean_{n-1} + (x - mean_{n-1}) / n
            cpu_mean = old_cpu_mean + (sample.cpu_percent - old_cpu_mean) / n
            mem_mean = old_mem_mean + (sample.memory_mb_peak - old_mem_mean) / n
            gpu_mean = old_gpu_mean + (sample.gpu_memory_mb_peak - old_gpu_mean) / n
            dur_mean = old_dur_mean + (sample.duration_seconds - old_dur_mean) / n
            # Max-of-peaks for memory metrics (eviction-candidate selection reads this)
            mem_max = max(old_mem_max, sample.memory_mb_peak)
            gpu_max = max(old_gpu_max, sample.gpu_memory_mb_peak)
            # SG-54: usage is ADDITIVE (cumulative) — merge-sum per unit name.
            try:
                usage_totals = json.loads(old_usage_totals_json) if old_usage_totals_json else {}
            except (TypeError, ValueError):
                usage_totals = {}
            for _k, _v in (sample.api_usage or {}).items():
                usage_totals[_k] = float(usage_totals.get(_k, 0.0)) + float(_v)

        conn.execute(
            "INSERT OR REPLACE INTO empirical_resources ("
            "instance_id, capability_name, config_hash, sample_count, success_count, "
            "cpu_percent_mean, memory_mb_peak_max, memory_mb_peak_mean, "
            "gpu_memory_mb_peak_max, gpu_memory_mb_peak_mean, "
            "duration_seconds_mean, last_observed, api_usage_totals"
            ") VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
            (
                instance_id, capability_name, config_hash, n, success_count,
                cpu_mean, mem_max, mem_mean, gpu_max, gpu_mean,
                dur_mean, sample.observed_at.isoformat(), json.dumps(usage_totals, sort_keys=True),
            ),
        )
        conn.commit()

# %% ../../nbs/core/empirical_store.ipynb #m-get-record
@patch
def get_record(
    self:LocalEmpiricalResourceStore,
    instance_id: str,
    config_hash: str,
) -> Optional[EmpiricalResourceRecord]:
    """Fetch the aggregated record for (instance_id, config_hash), or None."""
    if not self.db_path.exists():
        return None
    with self._conn() as conn:
        row = conn.execute(
            "SELECT instance_id, capability_name, config_hash, sample_count, success_count, "
            "cpu_percent_mean, memory_mb_peak_max, memory_mb_peak_mean, "
            "gpu_memory_mb_peak_max, gpu_memory_mb_peak_mean, "
            "duration_seconds_mean, last_observed, api_usage_totals "
            "FROM empirical_resources WHERE instance_id = ? AND config_hash = ?",
            (instance_id, config_hash),
        ).fetchone()
    return self._row_to_record(row) if row is not None else None

# %% ../../nbs/core/empirical_store.ipynb #m-list-records
@patch
def list_records(
    self:LocalEmpiricalResourceStore,
    capability_name: Optional[str] = None,
) -> List[EmpiricalResourceRecord]:
    """List all records, optionally filtered to a plugin."""
    if not self.db_path.exists():
        return []
    with self._conn() as conn:
        if capability_name is not None:
            rows = conn.execute(
                "SELECT instance_id, capability_name, config_hash, sample_count, success_count, "
                "cpu_percent_mean, memory_mb_peak_max, memory_mb_peak_mean, "
                "gpu_memory_mb_peak_max, gpu_memory_mb_peak_mean, "
                "duration_seconds_mean, last_observed, api_usage_totals "
                "FROM empirical_resources WHERE capability_name = ?",
                (capability_name,),
            ).fetchall()
        else:
            rows = conn.execute(
                "SELECT instance_id, capability_name, config_hash, sample_count, success_count, "
                "cpu_percent_mean, memory_mb_peak_max, memory_mb_peak_mean, "
                "gpu_memory_mb_peak_max, gpu_memory_mb_peak_mean, "
                "duration_seconds_mean, last_observed, api_usage_totals "
                "FROM empirical_resources",
            ).fetchall()
    return [self._row_to_record(r) for r in rows]

# %% ../../nbs/core/empirical_store.ipynb #m-delete-record
@patch
def delete_record(
    self:LocalEmpiricalResourceStore,
    instance_id: str,
    config_hash: str,
) -> bool:
    """Remove a record. Returns True if a row was deleted."""
    if not self.db_path.exists():
        return False
    with self._conn() as conn:
        cur = conn.execute(
            "DELETE FROM empirical_resources WHERE instance_id = ? AND config_hash = ?",
            (instance_id, config_hash),
        )
        conn.commit()
        return cur.rowcount > 0
