"""REMOVE-AFTER-OVERHAUL(option-c-cascade): class-identical legacy import
surface over the fractured interface.

Docs: https://cj-mills.github.io/cjm-plugin-systemcore/interface.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/core/interface.ipynb.

# %% auto #0
__all__ = ['PluginInterface', 'RELOAD_TRIGGER', 'WORKER_ENV_TEMPLATE_PLACEHOLDERS', 'FileBackedDTO', 'ConfigOption',
           'FieldOptions', 'EnvVarSpec', 'expand_worker_env_template', 'template_check_placeholders', 'plugin_action',
           'collect_plugin_actions']

# %% ../../nbs/core/interface.ipynb #15253925c3c2
# REMOVE-AFTER-OVERHAUL(option-c-cascade): legacy import surface; every name
# re-exports class-identically from the fractured homes. New code imports
# from cjm_plugin_system.core.capability / core.wire / core.adapter directly.
from cjm_plugin_system.core.capability import (
    RELOAD_TRIGGER,
    WORKER_ENV_TEMPLATE_PLACEHOLDERS,
    ConfigOption,
    FieldOptions,
    EnvVarSpec,
    expand_worker_env_template,
    template_check_placeholders,
    ToolCapability,
    plugin_action,
    collect_plugin_actions,
    _CR4MinimalCapability,
)
from .wire import FileBackedDTO

# The legacy name IS the new class (alias, not subclass): isinstance checks,
# MRO, and __abstractmethods__ are identical in both vocabularies.
PluginInterface = ToolCapability

# %% ../../nbs/core/interface.ipynb #ccd9c7fd7223
_all_ = ['RELOAD_TRIGGER', 'WORKER_ENV_TEMPLATE_PLACEHOLDERS', 'FileBackedDTO',
         'ConfigOption', 'FieldOptions', 'EnvVarSpec', 'expand_worker_env_template',
         'template_check_placeholders', 'PluginInterface', 'plugin_action',
         'collect_plugin_actions']
