"""FastAPI server that runs inside isolated plugin environments

Docs: https://cj-mills.github.io/cjm-plugin-systemcore/worker.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/core/worker.ipynb.

# %% auto #0
__all__ = ['EnhancedJSONEncoder', 'parent_monitor', 'create_app', 'run_worker']

# %% ../../nbs/core/worker.ipynb #50487ea2
import argparse
import asyncio
import contextvars
import dataclasses
import importlib
import json
import os
import sys
import threading
import time
from contextlib import asynccontextmanager
from datetime import datetime
from typing import Any, AsyncIterator, Dict, Generator

import psutil
import uvicorn
from fastapi import FastAPI, HTTPException, Request
from fastapi.responses import JSONResponse, StreamingResponse

from .errors import CapabilityCancelledError, map_bare_exception_to_job_error
from .platform import terminate_self

import logging
# CR-14: worker-process logging goes to the diagnostics STORE (structured
# records, contextvars-stamped job identity) when the proxy injected the
# env contract (CJM_DIAGNOSTICS_DB / CJM_WORKER_SESSION_ID / CJM_LOG_LEVEL);
# standalone/dev imports fall back to the pre-CR-14 stdout basicConfig.
# This module is a process entrypoint (SG-39 ownership note) — host code
# never imports it.
from .diagnostics_store import install_worker_diagnostics
install_worker_diagnostics()

from .capability import derive_structural_surface
from .journal_store import SubstrateEventType
from cjm_plugin_system.core.wire import (
    ACCOUNTS_HEADER, CallEnvelope, ENVELOPE_BODY_KEY, begin_account_capture,
    drain_accounts, record_account, set_call_envelope, wire_encode,
)

# %% ../../nbs/core/worker.ipynb #encoder
class EnhancedJSONEncoder(json.JSONEncoder):
    """JSON encoder that handles dataclasses and other common types.
    
    SG-52: datetime support added so JobError.occurred_at serializes cleanly
    when emitted via the typed `_job_error` terminal chunk in /execute_stream.
    """
    
    def default(
        self,
        o: Any # Object to encode
    ) -> Any: # JSON-serializable representation
        """Convert non-serializable objects to serializable form."""
        if dataclasses.is_dataclass(o) and not isinstance(o, type):
            return dataclasses.asdict(o)
        if isinstance(o, datetime):
            return o.isoformat()
        return super().default(o)

# %% ../../nbs/core/worker.ipynb #watchdog
def parent_monitor(
    ppid: int # Parent process ID to monitor
) -> None:
    """Monitor parent process and terminate self if parent dies.
    
    This implements the "Suicide Pact" pattern: if the Host process dies,
    the Worker must terminate itself to prevent zombie processes.
    """
    try:
        while True:
            parent = psutil.Process(ppid)
            if parent.status() == psutil.STATUS_ZOMBIE:
                raise psutil.NoSuchProcess(ppid)
            time.sleep(1)
    except (psutil.NoSuchProcess, ProcessLookupError):
        print(f"[Worker {os.getpid()}] Parent {ppid} gone. Shutting down.")
        # Use cross-platform self-termination
        terminate_self()

# %% ../../nbs/core/worker.ipynb #19319501
def _load_capability_instance(
    module_name: str, # Python module path (e.g., "my_plugin.plugin")
    class_name: str   # Plugin class name (e.g., "WhisperPlugin")
):                    # Instantiated plugin object
    """Dynamically load + instantiate the plugin class.

    Runs synchronously before app construction so a load failure terminates
    the worker process with exit code 1 (matches pre-lifespan behavior;
    loading must succeed for the worker to be useful at all).
    """
    try:
        module = importlib.import_module(module_name)
        capability_cls = getattr(module, class_name)
        return capability_cls()
    except Exception as e:
        print(f"FATAL: Failed to load {module_name}:{class_name} - {e}")
        sys.exit(1)

# %% ../../nbs/core/worker.ipynb #45de0055
def _make_lifespan(
    capability_instance  # The loaded plugin object (closure-captured for shutdown cleanup)
):                   # FastAPI lifespan async context manager
    """Build the FastAPI lifespan that invokes plugin.cleanup() on shutdown."""
    @asynccontextmanager
    async def lifespan(app: FastAPI) -> AsyncIterator[None]:
        """FastAPI lifespan replacing the deprecated @app.on_event("shutdown") path.

        Migration 2026-05-28: FastAPI deprecated `on_event` decorators in favor
        of the lifespan context manager (the DeprecationWarning fired in worker
        logs post-Session-A publish). Behavior is preserved verbatim:

        - Startup half is empty: the plugin is already instantiated above
          BEFORE the FastAPI app is constructed (load failure exits the
          process before lifespan runs). No async startup work is needed.
        - Shutdown half: invoke plugin.cleanup() before uvicorn exits.

        Session A 2026-05-27 rationale (still applies): both the parent_monitor
        watchdog (SIGTERM via terminate_self) and an external SIGTERM (e.g.,
        substrate's proxy stall-detection killing a wedged prefetch) route
        through uvicorn's graceful-shutdown path, which fires this lifespan
        teardown. Pre-Session-A the plugin's cleanup() hook was only invoked
        on the manager-driven unload_capability path — never on watchdog or
        stall-triggered termination — so capabilities that spawn grandchild
        subprocesses (Voxtral-vLLM's vLLM server is the driving case) leaked
        them as orphans whenever the worker died abnormally. Cleanup failures
        are swallowed-with-log because they must NOT prevent uvicorn shutdown.

        cleanup() is synchronous (PluginInterface contract). Calling a sync
        function from this async block briefly blocks the event loop during
        shutdown, which is acceptable — uvicorn is already winding down.
        """
        # Startup: nothing to do (plugin loaded above synchronously).
        yield
        # Shutdown: invoke plugin.cleanup() best-effort.
        try:
            cleanup = getattr(capability_instance, "cleanup", None)
            if cleanup is not None:
                cleanup()
        except Exception as e:
            try:
                import logging as _lg
                _lg.getLogger(__name__).warning(
                    f"plugin.cleanup() raised during worker shutdown: {e}"
                )
            except Exception:
                pass

    return lifespan

# %% ../../nbs/core/worker.ipynb #6b3a081a
def _register_identity_endpoints(
    app,             # FastAPI app under construction
    capability_instance, # The loaded plugin object
) -> None:
    """/health + /stats: worker identity + process-subtree telemetry."""
    @app.get("/health")
    def health_check() -> Dict[str, Any]:
        """Health check endpoint."""
        return {
            "status": "running",
            "pid": os.getpid(),
            "name": getattr(capability_instance, "name", "unknown"),
            "version": getattr(capability_instance, "version", "unknown")
        }

    # Closure-captured Process instance + per-child baseline cache (SG-40 pattern).
    # psutil.Process.cpu_percent() caches the prior CPU-time baseline ON THE
    # INSTANCE: separate Process() instances pointing at the same PID DON'T
    # share the baseline, so a one-shot prime at module-main-block can't help
    # a /stats handler that creates a fresh Process() each call. Keeping the
    # Process instance alive in this closure means the SECOND /stats call onward
    # returns real CPU% for the worker (the first prime-call happens below).
    # Children get the same treatment via _child_procs (keyed by PID; new children
    # are primed on first appearance, return 0% that call, real% thereafter).
    _worker_proc = psutil.Process()
    _worker_proc.cpu_percent()  # Prime worker baseline (next call returns delta).
    _child_procs: Dict[int, psutil.Process] = {}

    @app.get("/stats")
    def stats() -> Dict[str, Any]:
        """Return process-tree resource usage for the worker subprocess.

        Aggregates RSS + CPU% across the worker AND its descendants in one
        psutil.children() walk so subprocess-spawning capabilities (Voxtral-vLLM's
        managed vLLM server is the driving case) report subtree totals rather
        than worker-only values. `subtree_pids` is emitted alongside so the
        substrate's GPU-attribution helper can intersect with the system-
        monitor plugin's per-PID GPU enumeration without needing its own
        process-tree walk (which would duplicate this one).
        """
        worker_pid = os.getpid()

        # Single walk: descendants used for RSS + CPU% sums + subtree_pids list.
        try:
            descendants = _worker_proc.children(recursive=True)
        except (psutil.NoSuchProcess, psutil.AccessDenied):
            descendants = []  # No descendants → worker-only totals below.

        total_rss = _worker_proc.memory_info().rss
        total_cpu = _worker_proc.cpu_percent()  # Delta against the prime call in the closure.
        subtree_pids = [worker_pid]
        live_child_pids = set()
        for child in descendants:
            try:
                total_rss += child.memory_info().rss
                # Reuse the cached Process for delta-correctness (first call per child returns 0,
                # subsequent calls reflect actual CPU%). psutil.Process is hashable on (pid, create_time)
                # internally; we key by pid since descendants live shorter than the worker and pid recycling
                # within a single worker lifetime is extremely rare.
                cached = _child_procs.get(child.pid)
                if cached is None:
                    cached = child
                    cached.cpu_percent()  # Prime; this call returns 0.0
                    _child_procs[child.pid] = cached
                    total_cpu += 0.0
                else:
                    total_cpu += cached.cpu_percent()
                subtree_pids.append(child.pid)
                live_child_pids.add(child.pid)
            except (psutil.NoSuchProcess, psutil.AccessDenied):
                # Process died mid-walk OR we lack permission (rare for descendants); skip.
                pass

        # Evict cache entries for children that have exited (avoid unbounded growth
        # in long-running capabilities that frequently spawn-and-exit subprocesses).
        for stale_pid in list(_child_procs.keys()):
            if stale_pid not in live_child_pids:
                _child_procs.pop(stale_pid, None)

        return {
            "pid": worker_pid,
            "cpu_percent": total_cpu,  # Worker + descendants (subtree sum)
            "memory_rss_mb": total_rss / 1024 / 1024,
            "subtree_pids": subtree_pids,  # Worker + descendants; substrate intersects with sysmon GPU PIDs
            # SG-54: unit-agnostic measured usage the plugin reported via
            # report_usage() during the last execute (None if it reported none).
            "usage": getattr(capability_instance, "_last_api_usage", None),
        }

    @app.get("/structural_surface")
    def structural_surface() -> Dict[str, Any]:
        """Pass-2 Thread 3 live companion: re-derive the structural surface
        at runtime so the manager can compare it against the manifest's
        stored witness hash and flag `surface_drift` (the CR-8 idiom's
        third instance). Same derivation the introspection script records
        at install/regenerate time.
        """
        return derive_structural_surface(type(capability_instance))



# %% ../../nbs/core/worker.ipynb #a96c1c47
def _register_lifecycle_endpoints(
    app,             # FastAPI app under construction
    capability_instance, # The loaded plugin object
) -> None:
    """/initialize /prefetch /reconfigure /on_disable /on_enable /cleanup:
    the tool-capability lifecycle surface."""
    @app.post("/initialize")
    async def initialize(request: Request) -> Dict[str, str]:
        """Initialize or reconfigure the plugin."""
        try:
            config = await request.json()
            capability_instance.initialize(config)
            return {"status": "ok"}
        except Exception as e:
            raise HTTPException(status_code=400, detail=str(e))

    @app.post("/prefetch")
    def prefetch() -> Dict[str, str]:
        """CR-4: invoke the plugin's prefetch() hook for eager resource acquisition.
        
        Default PluginInterface.prefetch() is a no-op (SG-19 hook with opt-in
        semantics). Plugins override when downstream callers benefit from
        eager model-download / cache-warming. Errors surface as 500 with the
        exception detail; idempotent calls are the plugin's responsibility.
        """
        if not hasattr(capability_instance, "prefetch"):
            return {"status": "not_supported"}
        try:
            capability_instance.prefetch()
            return {"status": "prefetched"}
        except Exception as e:
            raise HTTPException(status_code=500, detail=str(e))

    @app.post("/reconfigure")
    async def reconfigure(request: Request) -> Dict[str, str]:
        """CR-4: invoke the plugin's reconfigure(old_config, new_config) hook.
        
        Request body: `{"old_config": {...}, "new_config": {...}}`. Default
        PluginInterface.reconfigure() delegates to reconfigure_with_triggers
        which walks RELOAD_TRIGGER metadata on the plugin's config_class.
        Plugins predating CR-4 (no config_class) land in the silent-no-op
        branch — substrate falls back to /initialize when reconfigure is a
        no-op.
        """
        if not hasattr(capability_instance, "reconfigure"):
            return {"status": "not_supported"}
        try:
            data = await request.json()
            old_config = data.get("old_config")
            new_config = data.get("new_config")
            capability_instance.reconfigure(old_config, new_config)
            return {"status": "reconfigured"}
        except Exception as e:
            raise HTTPException(status_code=500, detail=str(e))

    @app.post("/on_disable")
    def on_disable() -> Dict[str, str]:
        """CR-2: forward the substrate's on_disable signal to the loaded plugin.
        
        Worker stays alive; plugin's on_disable() hook gets a chance to
        release heavy resources (GPU memory, model files, etc.). Default
        PluginInterface.on_disable() is a no-op so capabilities that don't
        opt in see no behavior change.
        """
        if hasattr(capability_instance, 'on_disable'):
            try:
                capability_instance.on_disable()
                return {"status": "disabled"}
            except Exception as e:
                return {"status": "error", "detail": str(e)}
        return {"status": "not_supported"}

    @app.post("/on_enable")
    def on_enable() -> Dict[str, str]:
        """CR-2: forward the substrate's on_enable signal to the loaded plugin.
        
        Plugin can eagerly re-acquire heavy resources or rely on lazy
        re-acquisition via the next execute() call. Default
        PluginInterface.on_enable() is a no-op.
        """
        if hasattr(capability_instance, 'on_enable'):
            try:
                capability_instance.on_enable()
                return {"status": "enabled"}
            except Exception as e:
                return {"status": "error", "detail": str(e)}
        return {"status": "not_supported"}

    @app.post("/cleanup")
    def cleanup() -> Dict[str, str]:
        """Clean up plugin resources."""
        if hasattr(capability_instance, 'cleanup'):
            capability_instance.cleanup()
        return {"status": "cleaned"}



# %% ../../nbs/core/worker.ipynb #e93abae4
def _register_config_endpoints(
    app,             # FastAPI app under construction
    capability_instance, # The loaded plugin object
) -> None:
    """/config_schema /config /config_options: the config surface."""
    @app.get("/config_schema")
    def get_config_schema() -> Dict[str, Any]:
        """Return JSON Schema for plugin configuration."""
        if hasattr(capability_instance, 'get_config_schema'):
            return capability_instance.get_config_schema()
        return {}

    @app.get("/config")
    def get_config() -> Dict[str, Any]:
        """Return current plugin configuration."""
        if hasattr(capability_instance, 'get_current_config'):
            cfg = capability_instance.get_current_config()
            # Ensure dataclasses are serialized
            return json.loads(json.dumps(cfg, cls=EnhancedJSONEncoder))
        return {}

    @app.get("/config_options")
    def get_config_options() -> Dict[str, Any]:
        """CR-11: return live config option domains (dynamic schema enrichment)."""
        if hasattr(capability_instance, 'get_config_options'):
            opts = capability_instance.get_config_options()
            # FieldOptions/ConfigOption dataclasses -> JSON-serializable dicts
            return json.loads(json.dumps(opts, cls=EnhancedJSONEncoder))
        return {}



# %% ../../nbs/core/worker.ipynb #747f2011
def _load_adapters(
    capability_instance,  # The loaded tool-capability instance
    adapter_specs,    # List of "module:ClassName" impl specs (host-matched)
) -> Dict[str, Any]:  # task_name -> bound adapter instance
    """Instantiate task-adapter impls bound to this worker's tool (CR-17 pt 2).

    Each spec was matched HOST-side (adapter-manifest protocol members vs the
    capability's recorded structural surface) before reaching the worker, so a
    spec failing HERE is an INSTALL gap (interface lib missing from this env),
    not a compatibility miss — log loudly, skip, keep serving /execute.
    Binding convention: `AdapterClass(capability_instance)`; keyed by the class's
    `task_name` ClassVar.
    """
    adapters: Dict[str, Any] = {}
    for spec in adapter_specs or []:
        try:
            module_name, class_name = spec.rsplit(":", 1)
            mod = importlib.import_module(module_name)
            cls = getattr(mod, class_name)
            task_name = getattr(cls, "task_name", "") or ""
            if not task_name:
                logging.error(f"Adapter {spec!r} has no task_name; skipping")
                continue
            if task_name in adapters:
                logging.error(
                    f"Task {task_name!r} already bound to "
                    f"{type(adapters[task_name]).__name__}; skipping {spec!r}")
                continue
            adapters[task_name] = cls(capability_instance)
            logging.info(f"Bound adapter {class_name} for task {task_name!r}")
        except Exception as e:
            logging.error(f"Failed to load adapter {spec!r}: {e}")
    return adapters


# %% ../../nbs/core/worker.ipynb #0a62d840
def _apply_call_envelope(
    data: Dict[str, Any],  # The decoded request body
) -> None:
    """CR-14: decode the wire envelope into the worker-side contextvar.

    Set WITHOUT reset: ASGI handles each request in its own asyncio task, so
    the context (and the var) dies with the request — and for
    /execute_stream the response iteration runs in the SAME request task
    AFTER the endpoint returns, which is exactly why a reset-before-return
    would lose the identity (Starlette's iterate_in_threadpool copies the
    request task's context per chunk). An absent envelope leaves the var
    None — records stay honestly unattributed.

    CR-14 follow-up: also begins a fresh account-capture span (same no-reset
    semantics) so in-worker substrate-family accounts (TASK_ACCOUNT /
    RESULT_SAVED / CACHE_HIT) accumulate per call and ride back on the
    response header — see `_accounts_headers`.
    """
    env_wire = data.get(ENVELOPE_BODY_KEY)
    if env_wire:
        set_call_envelope(CallEnvelope.from_wire(env_wire))
    begin_account_capture()


def _accounts_headers() -> Dict[str, str]:
    """Drain the call span's recorded accounts into the response header dict.

    Empty dict when nothing was recorded (header absent — old hosts and
    account-less calls see byte-identical responses). ASCII JSON
    (`ensure_ascii` default) keeps the header latin-1-safe.
    """
    accounts = drain_accounts()
    if not accounts:
        return {}
    return {ACCOUNTS_HEADER: json.dumps(accounts, default=str)}


def _register_task_endpoints(
    app,             # FastAPI app under construction
    capability_instance, # The loaded plugin object
    adapters=None,   # task_name -> bound adapter instance (CR-17 pt 2; stage 4)
) -> None:
    """/execute /execute_stream /cancel /progress /task: the task channel.

    Stage 2 (typed wire layer): both result-serialization sites pass
    through `wire_encode`, so results whose DTO classes are registered
    via `@wire_type` cross the boundary in the tagged envelope and arrive
    typed at the proxy; unregistered results serialize exactly as before.

    CR-14 (stage 7): each call decodes the per-call envelope into the
    contextvar and carries it into the executor thread via
    `contextvars.copy_context()` (run_in_executor does NOT copy context by
    itself) — the diagnostics handler stamps every plugin log record with
    exact job identity, replacing the timestamp-window heuristic.

    CR-14 follow-up: the unary paths (/execute, /task) return recorded
    accounts on the `X-CJM-Accounts` response header (success AND the
    `_job_error` 500 — a failed call still reports the accounts recorded
    before the failure). The host journals them with `worker_reported=True`.
    """
    @app.post("/execute")
    async def execute(request: Request) -> Any:
        """Execute plugin's main functionality.
        
        Runs in a thread pool so the event loop stays free to serve
        concurrent requests (e.g., /progress polling during long operations).
        
        CR-4: resets the plugin's `_cancel_requested` flag before invoking
        execute() so cancellation doesn't leak from a previous job. After
        execute() returns or raises, leaves the flag in its post-call state
        (cancel() may have been called during cleanup; substrate decides what
        to do with that on next /cancel signal).
        
        CR-4: CapabilityCancelledError → HTTP 409 (operator-requested cancellation;
        distinct from 500's "real failure" so the proxy can surface a typed
        "cancelled" state to callers and JobQueue can render the job state
        accordingly per CR-6).
        """
        data = await request.json()
        args = data.get("args", [])
        kwargs = data.get("kwargs", {})
        _apply_call_envelope(data)  # CR-14: job identity + account span for this call
        
        # CR-4: reset cancellation flag before invoking execute() so stale
        # state from a previous job doesn't immediately raise.
        if hasattr(capability_instance, "_cancel_requested"):
            capability_instance._cancel_requested = False
        # SG-54: reset measured usage so a failed / usage-less call can't inherit
        # a prior run's usage when the substrate reads /stats post-execute.
        capability_instance._last_api_usage = None
        
        try:
            loop = asyncio.get_event_loop()
            # CR-14: copy_context AFTER the envelope set, so the executor
            # thread's plugin code (and its logger calls) sees the identity.
            ctx = contextvars.copy_context()
            result = await loop.run_in_executor(
                None, lambda: ctx.run(capability_instance.execute, *args, **kwargs)
            )
            # Typed wire envelope for registered result DTOs (stage 2);
            # EnhancedJSONEncoder still flattens unregistered dataclasses
            # and datetimes exactly as before.
            json_str = json.dumps(wire_encode(result), cls=EnhancedJSONEncoder)
            return JSONResponse(content=json.loads(json_str),
                                headers=_accounts_headers())
        except CapabilityCancelledError as e:
            # CR-4: cooperative cancellation surfaces as 409 Conflict so the
            # proxy can distinguish "operator cancelled" from "real plugin
            # failure" (500). The detail body carries the plugin name for
            # debugging context.
            raise HTTPException(status_code=409, detail=str(e))
        except Exception as e:
            import traceback
            traceback.print_exc()
            # SG-52 parity for the UNARY path (stage-3 stress-test finding,
            # ledger G7): the 500 body carries the SAME `{"_job_error":
            # <JobError dict>}` sentinel shape as the stream's terminal
            # chunk, so the proxy raises the typed exception client-side
            # (CapabilityResourceError et al) and CR-7's reactive retry can
            # actually see resource errors from plain /execute calls. The
            # old bare-string detail collapsed every failure to RuntimeError
            # host-side, leaving the retry path blind on this channel.
            job_error = map_bare_exception_to_job_error(
                e, capability_name=getattr(capability_instance, "name", "unknown"),
            )
            body = json.loads(json.dumps({"_job_error": job_error},
                                         cls=EnhancedJSONEncoder))
            return JSONResponse(status_code=500, content=body,
                                headers=_accounts_headers())

    _adapters = adapters or {}

    @app.post("/task")
    async def task_call(request: Request) -> Any:
        """Typed task-adapter dispatch (CR-17 pt 2; stage 4).

        Body: {"task": <task_name>, "method": <adapter method>, "kwargs": {...}}.
        Kwargs-only by design — typed task methods have named parameters; the
        explicit task channel never overloads `action=` (that stays the tool's
        native in-worker dispatch). Results pass through `wire_encode` (typed
        DTOs cross the boundary in the tagged envelope); failures carry the
        same `{"_job_error": ...}` 500 body as /execute (G7 typed unary error
        channel) so CR-7 retry sees typed categories from day one.

        CR-14 follow-up: the worker itself records a TASK_ACCOUNT for every
        adapter dispatch (zero plugin cooperation — derived at the substrate
        boundary): task, method, ok, duration. On failure the account carries
        ok=False + the JobError category, riding the same 500's header.
        """
        data = await request.json()
        task = data.get("task")
        method_name = data.get("method") or ""
        kwargs = data.get("kwargs", {})
        _apply_call_envelope(data)  # CR-14: job identity + account span for this call
        adapter = _adapters.get(task)
        if adapter is None:
            raise HTTPException(
                status_code=404,
                detail=f"No adapter bound for task {task!r} (bound: {sorted(_adapters)})")
        if not method_name or method_name.startswith("_"):
            raise HTTPException(
                status_code=404, detail=f"Invalid task method {method_name!r}")
        fn = getattr(adapter, method_name, None)
        if not callable(fn):
            raise HTTPException(
                status_code=404,
                detail=f"Task {task!r} adapter has no method {method_name!r}")

        # Cancel-flag + usage reset parity with /execute (the adapter drives
        # the same tool instance underneath).
        if hasattr(capability_instance, "_cancel_requested"):
            capability_instance._cancel_requested = False
        capability_instance._last_api_usage = None
        _t0 = time.monotonic()
        try:
            loop = asyncio.get_event_loop()
            ctx = contextvars.copy_context()  # CR-14: carry identity into the executor
            result = await loop.run_in_executor(None, lambda: ctx.run(lambda: fn(**kwargs)))
            json_str = json.dumps(wire_encode(result), cls=EnhancedJSONEncoder)
            record_account(SubstrateEventType.TASK_ACCOUNT.value, {
                "task": task, "method": method_name, "ok": True,
                "duration_s": round(time.monotonic() - _t0, 3),
            })
            return JSONResponse(content=json.loads(json_str),
                                headers=_accounts_headers())
        except CapabilityCancelledError as e:
            raise HTTPException(status_code=409, detail=str(e))
        except HTTPException:
            raise
        except Exception as e:
            import traceback
            traceback.print_exc()
            job_error = map_bare_exception_to_job_error(
                e, capability_name=getattr(capability_instance, "name", "unknown"),
            )
            record_account(SubstrateEventType.TASK_ACCOUNT.value, {
                "task": task, "method": method_name, "ok": False,
                "duration_s": round(time.monotonic() - _t0, 3),
                "error_category": job_error.category,
            })
            body = json.loads(json.dumps({"_job_error": job_error},
                                         cls=EnhancedJSONEncoder))
            return JSONResponse(status_code=500, content=body,
                                headers=_accounts_headers())

    @app.post("/execute_stream")
    async def execute_stream(request: Request) -> StreamingResponse:
        """Execute plugin with streaming response (NDJSON).
        
        SG-51: resets `_cancel_requested` at the start of iter_response (parity
        with /execute) so a leftover cancel flag from a previous job doesn't
        cause the first check_cancel() to raise on the new stream.
        
        SG-52: typed error chunks via `{"_job_error": <JobError dict>}` terminal
        chunk replace the undocumented `{"error": str(e)}` shape. The wire-format
        contract: ANY exception raised during streaming is converted via
        `map_bare_exception_to_job_error` (CR-5 default classification) and
        emitted as the final NDJSON line with the `_job_error` sentinel key.
        Plugin output chunks never carry that key, so consumers (proxy +
        downstream) can detect terminal errors with a single dict membership
        check. The proxy's execute_stream then raises a typed exception
        client-side, mirroring /execute's HTTP 409 → CapabilityCancelledError flow.

        CR-14: `_apply_call_envelope`'s no-reset semantics matter HERE — the
        response iteration runs in this request task after the endpoint
        returns, and each chunk's threadpool hop copies the task context,
        so the plugin's in-stream logger calls stay job-stamped.

        CR-14 follow-up honest limit: accounts do NOT ride this path —
        response headers are sent before execution ends. A terminal sentinel
        chunk (the `_job_error` dialect) is the seam-admitted carrier if a
        streaming adopter ever needs them.
        """
        data = await request.json()
        args = data.get("args", [])
        kwargs = data.get("kwargs", {})
        _apply_call_envelope(data)  # CR-14: identity persists through iteration

        def iter_response() -> Generator[str, None, None]:
            # SG-51: reset cancel flag so stale state from a previous job doesn't
            # immediately raise inside the plugin's execute_stream iterator.
            if hasattr(capability_instance, "_cancel_requested"):
                capability_instance._cancel_requested = False
            try:
                if hasattr(capability_instance, 'execute_stream'):
                    iterator = capability_instance.execute_stream(*args, **kwargs)
                else:
                    # Fallback: wrap single result
                    iterator = [capability_instance.execute(*args, **kwargs)]
                
                for chunk in iterator:
                    # Line-delimited JSON (NDJSON)
                    yield json.dumps(wire_encode(chunk), cls=EnhancedJSONEncoder) + "\n"
            except Exception as e:
                # SG-52: emit typed JobError as the terminal chunk. Proxy +
                # downstream consumers detect the `_job_error` sentinel key
                # and raise the corresponding typed exception client-side
                # (CapabilityCancelledError, CapabilityTransientError, etc.).
                job_error = map_bare_exception_to_job_error(
                    e, capability_name=getattr(capability_instance, "name", "unknown"),
                )
                yield json.dumps({"_job_error": job_error}, cls=EnhancedJSONEncoder) + "\n"

        return StreamingResponse(iter_response(), media_type="application/x-ndjson")

    @app.post("/cancel")
    def cancel() -> Dict[str, str]:
        """Cancel any running execution."""
        if hasattr(capability_instance, 'cancel'):
            try:
                capability_instance.cancel()
                return {"status": "cancelled"}
            except Exception as e:
                return {"status": "error", "detail": str(e)}
        return {"status": "not_supported"}

    @app.get("/progress")
    def get_progress() -> Dict[str, Any]:
        """Get current execution progress."""
        return {
            "progress": getattr(capability_instance, '_progress', 0.0),
            "message": getattr(capability_instance, '_status_message', "")
        }


# %% ../../nbs/core/worker.ipynb #580f8d04
def _register_monitor_endpoints(
    app,             # FastAPI app under construction
    capability_instance, # The loaded plugin object
    class_name: str, # Plugin class name (for 404 detail messages)
) -> None:
    """/get_system_status /list_processes: CR-3 typed MonitorPlugin accessors."""
    @app.post("/get_system_status")
    def get_system_status_endpoint() -> Dict[str, Any]:
        """CR-3: typed MonitorPlugin accessor. Returns SystemStats.to_dict().
        
        Status code taxonomy (intentional, per CR-3 review):
        - 404: plugin is not a MonitorPlugin (configuration error — don't mask).
              Substrate's `system_monitor` was wired to the wrong plugin.
        - 501: plugin is a MonitorPlugin but raised NotImplementedError from its
              get_system_status() default body (legacy monitor predating CR-3 that
              opted out). Proxy falls back to /execute("get_system_status").
        - 500: plugin's get_system_status() raised some other exception. Real
              failure; do not silently fall back.
        - 200: typed call succeeded; body is SystemStats.to_dict().
        """
        if not hasattr(capability_instance, 'get_system_status'):
            raise HTTPException(
                status_code=404,
                detail=(
                    f"Plugin {getattr(capability_instance, 'name', class_name)!r} "
                    f"is not a MonitorPlugin (no get_system_status method)."
                ),
            )
        try:
            stats = capability_instance.get_system_status()
        except NotImplementedError as exc:
            raise HTTPException(status_code=501, detail=str(exc) or "get_system_status not implemented")
        # Serialize via EnhancedJSONEncoder so SystemStats dataclass flattens
        # to its plain dict (and tolerates dict returns from non-typed monitors).
        if hasattr(stats, 'to_dict'):
            return stats.to_dict()
        return json.loads(json.dumps(stats, cls=EnhancedJSONEncoder))

    @app.post("/list_processes")
    def list_processes_endpoint() -> Any:
        """CR-3: typed MonitorPlugin accessor. Returns list of ProcessStats.to_dict().
        
        Same 404/501/500/200 taxonomy as /get_system_status. MonitorPlugin's
        default list_processes() returns `[]`, so non-implementing monitors
        return 200 with an empty list rather than 501.
        """
        if not hasattr(capability_instance, 'list_processes'):
            raise HTTPException(
                status_code=404,
                detail=(
                    f"Plugin {getattr(capability_instance, 'name', class_name)!r} "
                    f"is not a MonitorPlugin (no list_processes method)."
                ),
            )
        try:
            procs = capability_instance.list_processes()
        except NotImplementedError as exc:
            raise HTTPException(status_code=501, detail=str(exc) or "list_processes not implemented")
        # Each ProcessStats has .to_dict(); EnhancedJSONEncoder handles either
        # dataclass instances or pre-converted dicts uniformly.
        return json.loads(json.dumps(procs, cls=EnhancedJSONEncoder))



# %% ../../nbs/core/worker.ipynb #82f0d516
def create_app(
    module_name: str, # Python module path (e.g., "my_plugin.plugin")
    class_name: str,  # Plugin class name (e.g., "WhisperPlugin")
    adapter_specs=None # CR-17 pt 2: "module:ClassName" adapter impl specs to bind in-worker
) -> FastAPI: # Configured FastAPI application
    """Create FastAPI app that hosts the specified plugin.

    NB-2 reshape (stage 2): a thin assembler — load the plugin, build the
    lifespan, register the endpoint groups. Endpoint behavior lives in the
    module-level `_register_*` helpers above.
    """
    capability_instance = _load_capability_instance(module_name, class_name)
    adapters = _load_adapters(capability_instance, adapter_specs)
    app = FastAPI(title="Plugin Worker", lifespan=_make_lifespan(capability_instance))
    _register_identity_endpoints(app, capability_instance)
    _register_lifecycle_endpoints(app, capability_instance)
    _register_config_endpoints(app, capability_instance)
    _register_task_endpoints(app, capability_instance, adapters)
    _register_monitor_endpoints(app, capability_instance, class_name)
    return app

# %% ../../nbs/core/worker.ipynb #main-block
def run_worker() -> None:
    """CLI entry point for running the worker."""
    parser = argparse.ArgumentParser(description="Universal Plugin Worker")
    parser.add_argument("--module", required=True, help="Plugin module path")
    parser.add_argument("--class", dest="class_name", required=True, help="Plugin class name")
    parser.add_argument("--adapters", required=False, default="",
                        help="Comma-separated adapter impl specs 'module:ClassName' (CR-17 pt 2)")
    # SG-4: parent-bound listening-socket FD inheritance closes the
    # bind-then-close-then-reopen TOCTOU race. --fd is preferred on Unix;
    # --port stays as the Windows fallback (pass_fds is Unix-only) and as a
    # diagnostic escape hatch when invoking the worker directly.
    parser.add_argument("--fd", type=int, required=False, default=None,
                        help="Inherited listening-socket file descriptor (Unix; preferred)")
    parser.add_argument("--port", type=int, required=False, default=None,
                        help="Port to bind (used when --fd is not provided)")
    parser.add_argument("--ppid", type=int, required=False, help="Parent PID to monitor")
    args = parser.parse_args()

    if args.fd is None and args.port is None:
        parser.error("one of --fd or --port is required")

    # Start watchdog if parent PID provided
    if args.ppid:
        watchdog = threading.Thread(
            target=parent_monitor,
            args=(args.ppid,),
            daemon=True
        )
        watchdog.start()

    adapter_specs = [s.strip() for s in (args.adapters or "").split(",") if s.strip()]
    app = create_app(args.module, args.class_name, adapter_specs=adapter_specs)
    if args.fd is not None:
        uvicorn.run(app, fd=args.fd, log_level="warning")
    else:
        uvicorn.run(app, host="127.0.0.1", port=args.port, log_level="warning")

# %% ../../nbs/core/worker.ipynb #module-main
#| eval: false
import sys

if __name__ == "__main__" and "ipykernel" not in sys.modules:
    run_worker()
