"""One-call factory that assembles a CapabilityManager + JobQueue + capability bindings — closes the demo-app boilerplate duplication audited across 5 substrate consumers.

Docs: https://cj-mills.github.io/cjm-substratebootstrap.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/bootstrap.ipynb.

# %% auto #0
__all__ = ['CapabilitySpec', 'Pipeline', 'create_pipeline']

# %% ../nbs/bootstrap.ipynb #exports
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, Iterable, List, Mapping, Optional, Tuple, Union

import logging

from .core.manager import CapabilityBinding, CapabilityManager
from .core.queue import JobQueue
from .core.scheduling import ResourceScheduler

_logger = logging.getLogger(__name__)

CapabilitySpec = Union[str, Tuple[str, Optional[Dict[str, Any]]], Mapping[str, Any]]

# %% ../nbs/bootstrap.ipynb #pipeline-class
@dataclass
class Pipeline:
    """Assembled substrate stack: manager + queue + capability bindings."""
    manager: CapabilityManager  # Discovery + lifecycle
    queue: JobQueue  # Job submission + scheduling
    bindings: Dict[str, CapabilityBinding] = field(default_factory=dict)  # Capability name -> bound view
    
    async def start(self) -> None:
        """Start the job queue's background processor."""
        await self.queue.start()
    
    async def stop(self) -> None:
        """Stop the job queue and unload all capabilities."""
        await self.queue.stop()
        self.manager.unload_all()
    
    async def __aenter__(self) -> "Pipeline":
        await self.start()
        return self
    
    async def __aexit__(self, exc_type, exc, tb) -> None:
        await self.stop()

# %% ../nbs/bootstrap.ipynb #spec-helpers
def _normalize_spec(
    spec: CapabilitySpec  # Raw spec from caller
) -> Tuple[str, Optional[Dict[str, Any]]]:  # (capability_name, optional config)
    """Normalize a capability spec into a `(name, config)` pair.
    
    Accepts a bare string, a `(name, config)` tuple, or a mapping with a 'name'
    key (config under 'config' or the mapping itself minus 'name').
    """
    if isinstance(spec, str):
        return spec, None
    if isinstance(spec, tuple):
        if len(spec) == 1:
            return spec[0], None
        if len(spec) == 2:
            return spec[0], spec[1]
        raise ValueError(f"capability spec tuple must be (name,) or (name, config); got {spec!r}")
    if isinstance(spec, Mapping):
        if "name" not in spec:
            raise ValueError(f"capability spec mapping missing 'name' key: {spec!r}")
        name = spec["name"]
        if "config" in spec:
            return name, spec["config"]
        return name, None
    raise TypeError(f"unsupported capability spec type: {type(spec).__name__}")

# %% ../nbs/bootstrap.ipynb #factory
def create_pipeline(
    capabilities: Optional[Iterable[CapabilitySpec]] = None,  # Capabilities to discover + load
    scheduler: Optional[ResourceScheduler] = None,  # Resource policy (default: permissive)
    system_monitor: Optional[str] = None,  # Capability name to register as system monitor
    search_paths: Optional[List[Path]] = None,  # Custom manifest search paths
    queue_kwargs: Optional[Dict[str, Any]] = None,  # Extra kwargs forwarded to JobQueue
    strict: bool = True,  # SG-5 strict config validation on each load
) -> Pipeline:  # Assembled stack ready to start
    """Assemble a CapabilityManager + JobQueue + capability bindings in one call.
    
    Steps performed:
      1. Construct CapabilityManager with the given scheduler + search paths
      2. discover_manifests()
      3. For each spec in `capabilities`: load the capability and create a CapabilityBinding
      4. If `system_monitor` is set, register that capability as the sys-mon
      5. Construct JobQueue (NOT started — caller starts via context manager)
    
    Capabilities that fail to load are logged but do not raise; their entries are
    omitted from `Pipeline.bindings`. Use the returned `Pipeline.manager` to
    inspect which loads succeeded.
    """
    manager = CapabilityManager(scheduler=scheduler, search_paths=search_paths)
    manager.discover_manifests()
    
    bindings: Dict[str, CapabilityBinding] = {}
    for spec in (capabilities or []):
        name, config = _normalize_spec(spec)
        binding = manager.bind(name, default_config=config or {})
        try:
            loaded = binding.load(config=config, strict=strict)
        except Exception as e:
            _logger.error("Failed to load capability %s: %s", name, e)
            continue
        if loaded:
            bindings[name] = binding
        else:
            _logger.warning("Capability %s did not load; omitted from pipeline.bindings", name)
    
    if system_monitor:
        manager.register_system_monitor(system_monitor)
    
    queue = JobQueue(manager=manager, **(queue_kwargs or {}))
    return Pipeline(manager=manager, queue=queue, bindings=bindings)
