"""Per-(input-content, config) deterministic cache directories for capability outputs

Docs: https://cj-mills.github.io/cjm-plugin-systemutils/cache_paths.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/utils/cache_paths.ipynb.

# %% auto #0
__all__ = ['cache_dir_for_config', 'list_cache_entries', 'prune_cache_for_input']

# %% ../../nbs/utils/cache_paths.ipynb #cell-imports
import logging
import os
import re
import shutil
import sqlite3
import threading
from contextlib import contextmanager
from pathlib import Path
from typing import Any, Dict, Iterator, List, Optional, Set, Union

from ..core.empirical_store import compute_config_hash
from .hashing import hash_file

_logger = logging.getLogger(__name__)

# %% ../../nbs/utils/cache_paths.ipynb #cell-sanitize-stem
# Filesystem-portable max stem length. Linux + macOS handle 255-byte filenames;
# Windows MAX_PATH considerations + Unicode encoding make 100 chars a safe
# operator-readable cap. Operators ARE going to inspect these directories;
# long stems are noise.
_MAX_STEM_LEN = 100

# Replace characters that are problematic on at least one major filesystem.
# Windows reserves these explicitly; Linux/macOS tolerate them but operators
# don't want them in path components either.
_UNSAFE_CHARS = re.compile(r'[<>:"/\\|?*\x00-\x1f]')


def _sanitize_stem(
    input_path: Union[str, Path],  # Path whose stem to sanitize
) -> str:                            # Filesystem-portable stem string
    """Return a filesystem-portable, length-capped version of input_path's stem.

    Steps: take `Path(input_path).stem`, replace unsafe characters with `_`,
    strip leading/trailing dots + whitespace (Windows path-component rule),
    length-cap to `_MAX_STEM_LEN`. Empty stems (degenerate paths like `.`)
    return `_` so callers always get a usable path component.
    """
    raw = Path(str(input_path)).stem
    if not raw:
        return "_"
    cleaned = _UNSAFE_CHARS.sub("_", raw)
    cleaned = cleaned.strip(". \t")
    if not cleaned:
        return "_"
    return cleaned[:_MAX_STEM_LEN]

# %% ../../nbs/utils/cache_paths.ipynb #cell-stat-cache
_stat_cache_lock = threading.Lock()

# %% ../../nbs/utils/cache_paths.ipynb #fn-get-stat-cache-path
def _get_stat_cache_path() -> Optional[Path]:
    """Locate the stat-cache SQLite path under the substrate's data dir.

    Returns the configured `cfg.data_dir / "input_hash_cache.db"` when the
    substrate config is available, falling back to `~/.cjm/input_hash_cache.db`
    when get_config() raises (e.g., during early-init tests). Returns None
    only when neither resolves — callers then skip caching entirely.
    """
    try:
        from cjm_plugin_system.core.config import get_config
        cfg = get_config()
        if cfg.data_dir is not None:
            return cfg.data_dir / "input_hash_cache.db"
    except Exception:
        pass
    # Fallback: per-user default. Match the convention CR-2's
    # LocalCapabilityConfigStore + CR-7's LocalEmpiricalResourceStore use.
    home = Path.home()
    return home / ".cjm" / "input_hash_cache.db"

# %% ../../nbs/utils/cache_paths.ipynb #fn-ensure-stat-cache-schema
def _ensure_stat_cache_schema(conn: sqlite3.Connection) -> None:
    """Create the stat-cache table + indices if not present."""
    conn.execute("PRAGMA journal_mode=WAL")
    conn.execute("""
        CREATE TABLE IF NOT EXISTS input_hash_cache (
            path TEXT NOT NULL,
            mtime_ns INTEGER NOT NULL,
            size INTEGER NOT NULL,
            content_hash TEXT NOT NULL,
            PRIMARY KEY (path, mtime_ns, size)
        )
    """)
    conn.commit()

# %% ../../nbs/utils/cache_paths.ipynb #fn-hash-input-with-stat-cache
def _hash_input_with_stat_cache(
    input_path: Path,                      # File whose content hash we need
    cache_path: Optional[Path] = None,     # Explicit cache DB path (default: substrate-resolved)
    *,
    skip_cache: bool = False,              # If True, bypass cache entirely (compute always)
) -> str:                                   # Hash string in "algo:hexdigest" format
    """Return the SHA-256 content hash of `input_path`, with stat-cache memoization.

    Fast path: stat the file, look up `(absolute_path, mtime_ns, size)` in the
    SQLite cache; cache hit returns in microseconds. Cold path: `hash_file`
    streams the file content, then writes the result to the cache.

    `skip_cache=True` bypasses the cache entirely — useful for callers that
    KNOW the file content changed (e.g., a capability just wrote it and wants
    to record the canonical hash without polluting the cache with intermediate
    states).

    File not found / unreadable → propagates the underlying OSError. Cache
    DB errors are LOG-and-FALLBACK to direct hashing — the cache is an
    optimization, not a correctness invariant.
    """
    p = Path(input_path).resolve()
    if not p.exists():
        # Let hash_file's open() raise the FileNotFoundError with a clear path.
        return hash_file(p)

    if skip_cache:
        return hash_file(p)

    try:
        st = p.stat()
        mtime_ns = st.st_mtime_ns
        size = st.st_size
    except OSError as e:
        _logger.debug(f"stat failed for {p!r}: {e}; falling back to direct hash")
        return hash_file(p)

    db_path = cache_path or _get_stat_cache_path()
    if db_path is None:
        return hash_file(p)
    # Ensure the parent dir exists; the substrate creates other store dirs
    # the same way in CR-2 / CR-7.
    try:
        db_path.parent.mkdir(parents=True, exist_ok=True)
    except OSError as e:
        _logger.debug(f"cache dir {db_path.parent!r} unavailable: {e}")
        return hash_file(p)

    with _stat_cache_lock:
        try:
            conn = sqlite3.connect(str(db_path))
            try:
                _ensure_stat_cache_schema(conn)
                row = conn.execute(
                    "SELECT content_hash FROM input_hash_cache "
                    "WHERE path = ? AND mtime_ns = ? AND size = ?",
                    (str(p), mtime_ns, size),
                ).fetchone()
                if row is not None:
                    return row[0]
                # Cold path: compute + cache.
                content_hash = hash_file(p)
                conn.execute(
                    "INSERT OR REPLACE INTO input_hash_cache "
                    "(path, mtime_ns, size, content_hash) VALUES (?, ?, ?, ?)",
                    (str(p), mtime_ns, size, content_hash),
                )
                conn.commit()
                return content_hash
            finally:
                conn.close()
        except sqlite3.Error as e:
            _logger.warning(
                f"stat-cache DB error at {db_path!r}: {e}; falling back to direct hash"
            )
            return hash_file(p)

# %% ../../nbs/utils/cache_paths.ipynb #cell-cache-dir-for-config
def cache_dir_for_config(
    capability_data_dir: Union[str, Path],     # The capability's own data subdirectory (typically <cfg.capability_data_dir>/<capability_name>)
    input_path: Union[str, Path],           # The input file the capability operates on
    action: str,                            # The capability action name (e.g., "segment_audio", "convert", "execute")
    config_dict: Dict[str, Any],            # The capability's effective config for this action
    *,
    input_hash_length: int = 6,             # Truncation length for the input content hash in the directory name
    config_hash_length: int = 12,           # Truncation length for the config hash in the directory name
    create: bool = True,                    # Auto-create the directory (parents=True, exist_ok=True)
    hash_input_content: bool = True,        # If False, hash str(input_path) instead (e.g., URL inputs)
    skip_input_cache: bool = False,         # If True, bypass the stat-cache (always recompute content hash)
) -> Path:                                   # The deterministic cache directory path
    """Return (and optionally create) a per-(input-content, config) cache directory.

    Path layout::

        <capability_data_dir>/<action>/<sanitized-stem>/<input_hash[:N]>_<config_hash[:M]>/

    The same `(input_content, action, config_dict)` always resolves to the same
    path; any change to input content OR config produces a different path. This
    means:

    1. Different configs go to different directories — no silent overwrite.
    2. Stale-artifact accumulation is impossible — each unique
       `(input_content, config)` tuple has its OWN directory.
    3. For chained capability sequences, upstream config changes propagate through
       content changes: if capability A's output content depends on A's config and
       capability B reads that output, B's cache key automatically reflects A's
       config indirectly.

    `hash_input_content=False` switches to hashing the string form of
    `input_path` instead of file content — for capabilities whose "input" is a URL,
    a database row ID, or another non-file identifier. Sequence chaining via
    content propagation only works for true file inputs.

    `skip_input_cache=True` recomputes the input content hash even if the
    stat-cache has a record. Useful for capabilities that just wrote the input file
    and want to record its canonical hash without stale-cache risk.

    Raises FileNotFoundError if `input_path` doesn't exist and
    `hash_input_content=True`. Raises OSError on directory-create failure
    when `create=True`.
    """
    base = Path(capability_data_dir)
    stem = _sanitize_stem(input_path)
    if hash_input_content:
        input_hash = _hash_input_with_stat_cache(
            Path(input_path), skip_cache=skip_input_cache,
        )
    else:
        # Non-file input — hash the string form. Stem still derived from the
        # input string so operator-inspectable directories remain readable.
        from cjm_plugin_system.utils.hashing import hash_bytes
        input_hash = hash_bytes(str(input_path).encode("utf-8"))
    # Both hashes come back as "sha256:hexdigest"; strip the algo prefix
    # before truncation so the directory component is pure hex.
    input_hex = input_hash.split(":", 1)[1] if ":" in input_hash else input_hash
    config_hash = compute_config_hash(config_dict)
    config_hex = config_hash.split(":", 1)[1] if ":" in config_hash else config_hash
    leaf = f"{input_hex[:input_hash_length]}_{config_hex[:config_hash_length]}"
    out_dir = base / action / stem / leaf
    if create:
        out_dir.mkdir(parents=True, exist_ok=True)
    return out_dir

# %% ../../nbs/utils/cache_paths.ipynb #cell-companions
def list_cache_entries(
    capability_data_dir: Union[str, Path],  # The capability's own data subdirectory
    input_path: Union[str, Path],        # The input file whose cache entries to list
    action: str,                          # The capability action name
) -> List[Path]:                          # All config-hash directories for this (input, action)
    """Enumerate all per-config cache directories for a given (input, action).

    Returns the paths of every `<input_hash>_<config_hash>` directory under
    `<capability_data_dir>/<action>/<sanitized-stem>/`. Each entry corresponds to
    a unique `(input_content, config)` tuple — operators can inspect their
    contents, diff them, or pass selected ones to `prune_cache_for_input` to
    keep them through a sweep.

    Returns an empty list if the parent directory doesn't exist (capability never
    ran this action for this input).
    """
    base = Path(capability_data_dir)
    stem = _sanitize_stem(input_path)
    parent = base / action / stem
    if not parent.exists():
        return []
    return sorted(p for p in parent.iterdir() if p.is_dir())


def prune_cache_for_input(
    capability_data_dir: Union[str, Path],  # The capability's own data subdirectory
    input_path: Union[str, Path],        # The input file whose cache entries to prune
    action: str,                          # The capability action name
    *,
    keep: Optional[Set[Path]] = None,    # Paths to preserve through the sweep (returns by list_cache_entries)
    dry_run: bool = False,                # If True, return what WOULD be deleted without touching filesystem
) -> List[Path]:                          # Paths that were (or would be) deleted
    """Delete per-config cache directories for `(input, action)`, optionally
    preserving a `keep` set.

    Pairs with `list_cache_entries` for inspect-then-prune workflows: list
    candidates, choose which to keep, then call prune with the keep set.
    `keep=None` deletes ALL entries.

    `dry_run=True` returns the would-delete list without touching the
    filesystem — useful for operator confirmation before destructive ops.

    Returns the list of deleted (or would-delete) paths.
    """
    keep_set = keep or set()
    targets = list_cache_entries(capability_data_dir, input_path, action)
    deleted: List[Path] = []
    for entry in targets:
        if entry in keep_set:
            continue
        if not dry_run:
            shutil.rmtree(entry, ignore_errors=True)
        deleted.append(entry)
    return deleted
