"""Shared cryptographic hashing primitives for content integrity verification

Docs: https://cj-mills.github.io/cjm-substrateutils/hashing.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/utils/hashing.ipynb.

# %% auto #0
__all__ = ['hash_bytes', 'hash_file', 'verify_hash', 'hash_dict_canonical']

# %% ../../nbs/utils/hashing.ipynb #cell-imports
import hashlib
import json
from pathlib import Path
from typing import Any, Dict, Optional, Union

# %% ../../nbs/utils/hashing.ipynb #cell-hash-bytes
def hash_bytes(
    content: bytes,  # Byte content to hash
    algo: str = "sha256"  # Hash algorithm name (e.g., "sha256", "sha3_256")
) -> str:  # Hash string in "algo:hexdigest" format
    """Compute a hash of byte content."""
    return f"{algo}:{hashlib.new(algo, content).hexdigest()}"

# %% ../../nbs/utils/hashing.ipynb #cell-hash-file
def hash_file(
    path: Union[str, Path],  # Path to file to hash
    algo: str = "sha256",  # Hash algorithm name
    chunk_size: int = 8192  # Read chunk size in bytes
) -> str:  # Hash string in "algo:hexdigest" format
    """Stream-hash a file without loading it entirely into memory."""
    h = hashlib.new(algo)
    with open(path, 'rb') as f:
        while True:
            chunk = f.read(chunk_size)
            if not chunk:
                break
            h.update(chunk)
    return f"{algo}:{h.hexdigest()}"

# %% ../../nbs/utils/hashing.ipynb #cell-verify-hash
def verify_hash(
    content: bytes,  # Content to verify
    expected: str  # Expected hash in "algo:hexdigest" format
) -> bool:  # True if content matches expected hash
    """Verify content against an expected hash string."""
    algo, _ = expected.split(":", 1)
    return hash_bytes(content, algo) == expected

# %% ../../nbs/utils/hashing.ipynb #4a22de34
def hash_dict_canonical(
    data: Optional[Dict[str, Any]],  # Dict to hash (or None — treated as {})
    algo: str = "sha256",  # Hash algorithm name
) -> str:  # Hash string in "algo:hexdigest" format
    """Hash a dict via canonical JSON encoding.
    
    Canonicalization: `json.dumps(data, sort_keys=True, separators=(",", ":"))`.
    Sorted keys eliminate dict-insertion-order variance; minimal separators
    eliminate whitespace variance. Result is deterministic across Python
    versions and machines.
    """
    canonical = json.dumps(data or {}, sort_keys=True, separators=(",", ":"))
    return hash_bytes(canonical.encode("utf-8"), algo=algo)
